rancher/elemental-operator

README.md

Part of https://github.com/rancher/elemental-toolkit/issues/1380
I've just renamed docs here and fixed a typo. I backed off to do change to the code/tests as could conflict with @paynejacob work.

Fixup docs, rename to elemental in README

---

.goreleaser.yaml
Makefile

Fixes the build of operator/installer so they support the emulatedTPM
out of the box (You cant compile them with GCO_ENABLED=0)
Also adds the installer to goreleaser so its also published on new
releases

Fix building the operator/installer with emulatedTPM

---

cmd/operator/register/root.go

Enable local plans execution in the rancher-system-agent.
Just a matter of adding a couple of options to the config created by the elemental-operator.

elemental-operator register: enable local plans

---

.github/workflows/docker.yaml
.github/workflows/e2e.yaml
.goreleaser.yaml
Dockerfile
Makefile
cmd/operator/operator/root.go
cmd/operator/register/root.go
pkg/version/version.go

Both for installer and operator, the first thing they now do is log the
version, commit and commit date on start
Fixes #37 

Log the version, commit and commit date on start

---

cmd/operator/register/root.go

Pass debug flag to elemental client if requested

---

Makefile

Just a matter to install and not "get" ginkgo otherwise we break every time a new ginko release is out I guess.
---
$make unit-tests
go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
go get github.com/onsi/gomega/...
ginkgo -r -v  --covermode=atomic --coverprofile=coverage.out -p -r ./pkg/...
Failed to compile config:
config_suite_test.go:22:2: missing go.sum entry for module providing package github.com/onsi/ginkgo/v2 (imported by github.com/rancher/elemental-operator/pkg/config); to add:
go get -t github.com/rancher/elemental-operator/pkg/config
FAIL    github.com/rancher/elemental-operator/pkg/config [setup failed]
FAIL
no composite coverage computed: all suites included programatically focused specs
Ginkgo ran 3 suites in 661.375947ms
There were failures detected in the …

Fix "make unit-tests"

---

cmd/operator/register/root.go

This PR ensures the bare minimum configuration to call `elemental-operator register` from the installed system is stored to the installed system during the installation.
On installed system calling `elemental-operator register /oem/registration` will rerun the registration process without applying any change on the current system (no installation neither cloud-config download). Can be used to apply labels to machine inventories and similar operations.
Related to rancher/elemental-cli#284 and #63

Store registration yaml in installed system

---

cmd/operator/register/root.go

Make /oem/registration the default configuration dir for elemental-operator client

---

cmd/operator/register/root.go

We were not checking for an error on the path before checking for other
things so that could lead to a runtime error.
This patch just makes sure that before doing anything we check that the
lstat of the path did not give an error, otherwise it skips that path
for any further checks
Also exit with a message on no registrationURL. I cant live without that any longer :D

[register] Check for path error before doing anything

---

Makefile
scripts/setup-kind-cluster.sh
tests/e2e/do_nothing_test.go

This target (ab)uses the ginkgo BeforeSuite to have a ready-to-test
cluster with all prerequisites installed for easy testing.
It will build the docker image for the operator, build the chart
pointing to that image, setup a kind cluster, load the docker image
locally built into the cluster and run an empty test which is done so
the BeforeSuite is run, which installs all the needed charts and the
operator into the system.

Add a target to setup a clean cluster

---

pkg/config/config.go

we need also to add the 'mapstructure' tag to the CACert field to allow proper yaml decode from viper: viper takes care of
merging the configuration from the yaml file and uses mapstructure for decoding the yaml file.
The only fields merged by viper are the URL and the CACert, so added the mapstructure tags only to those.
Part of #51

ensure all the structs include proper yaml labels

---

cmd/operator/register/root.go
go.mod
go.sum

Add some more logs (mainly from config read)

---

pkg/tpm/register.go

When we pass a CACert we enfore the certificate we get from the Register.URL
to be signed by the passed CACert: let's keep also the System CAs in the pool
of allowed CAs in order to accept also imported certificates signed by public
trusted CAs.
Fixes #84

elemental-operator register: keep system CAs when passing a custom CA

---

tests/e2e/e2e_suite_test.go

Due to our integration with rancher-system-agent we need to bump the
version, otherwise the rancher-system-agent will fail to launch

Bump rancher version

---

pkg/controllers/machineinventoryselector/bootstrap.go
pkg/controllers/machineinventoryselector/controller.go

Not usre why we were using the elemental:// providerID while this should
be something like k3s://
Not only that but it was blocking the correct health check of the
clusters due to not finding the provider.
Also drops the provider config override from rke2 as it was setting it
to an empty value. We should be able to restore if it proves to be
needed but doesnt seem to.

Drop setting a custom providerID

---

pkg/controllers/machineinventoryselector/bootstrap.go

Fixes https://github.com/rancher/elemental/issues/221
Looks like the name change once rebooted was causing more problems that what it looked like. On the first deployment, some of the pods would be launched with the hostname as part of them, i.e. `cloud-controller-manager-m-qemu-standard-pc-q35-ich9-2009-1d566d99-d81a-49ae-b0bb-3` and that was ok, but the deployment would also change the node name to be `rancher-NUMBERS` which only took place after a restart.
The deployment would then try to recover, and bring up missing pods with that name, but would also bring up the old pods with the old name, causing some pods to fight for resources or directly crash constantly.
This patch adds an extra config to the k3s/rk2 configurations to set the `node-name` for the deployment agents and pods to …

Set a fixed name config for rke/k3s deployments

---

pkg/server/register.go

Labels and Annotations are initialized the same way in
createMachineInventory()

operator: drop duplicated MachineInventory init code

---

pkg/server/register.go

All the parameters are then used by tpm.Register... we need them if available in the MachineRegistration Spec.

operator: pass all the registration fields on unauthenticated query

---

.github/workflows/docker.yaml
.github/workflows/e2e.yaml

On master merge, push the image also to elemental-operator-ci adding
also the latest tag, so it can be tracked by external sources and alwasy
use the latest master merge
Not that in the case of the elemental-operator we also push the PRs to
elemental-operator-ci but those are only used temporarily for e2e
testing and latest tag will only track master merges

Push master merges to elemental-operator-ci

---

Makefile
cmd/support/main.go

Allows to gather info about the running node, hostname, k8s resources,
systemd logs, etc..

Add a elemental-support binary

---

pkg/controllers/machineinventoryselector/bootstrap.go

For elemental /etc/hostname -> /usr/local/etc/hostname, this file has to be updated
to make change persistent.
Fixes https://github.com/rancher/elemental/issues/221

Set fixed hostname and make it persistent

---

Dockerfile

It makes sense to bundle the support binary in the register container as
they are used on the nodes
Also separate the go build stuff between operator and register so it
doest take that much time

Bundle support bin with register

---

tests/e2e/e2e_suite_test.go

Since https://github.com/kubernetes/ingress-nginx/pull/8877 was merged
the ingress-nginx project does not longer provide versioned deploy files
This should fix our end2end tests

[tests] fix nginx deploy url

---

.github/workflows/build.yaml

Useful to create special binaries and give them to people for quick
testing if we store those built binaries from PRs/main branch

Store binary artifacts on PR/master

---

chart/templates/deployment.yaml

If its empty let the operator set the default value instead of passing a
flag with an empty value

[chart] only add default-registry if specified

---

chart/values.yaml
cmd/operator/operator/root.go

Make sure we have a decent description for the --operator-image flag as
that is used down the line by the syncer to run the display command and
gather the results from the version syncer.
Also remove the default value for the flag. It makes no sense to have a
default value if we mark a flag as required, as that value will always
be overwritten by the flag.
Fixes #119 

Remove default value for flag and expand description

---

pkg/server/register.go
pkg/tpm/register.go

This generates several X-Cattle-Smbios-NUMER headers when sending the
data to the operator in order to limit the max size of each individual
header to 7Kb. By default nginx is configured with a max of 8Kb header
and will return a 400 error if the headers excess that size.
As we currently use a GET+Websocket to go trougth the challenge/response
of TPM, this is the easiest implementation to workaround the issue.

Split header into 7Kb of data

---

pkg/server/register.go
pkg/server/register_test.go

Adds backwards compatibility for clients sending old headers with smbios
data

Backwards compatibility for smbios headers

---

pkg/server/register.go
pkg/server/server.go
pkg/tpm/auth_tpm.go

Till now the TPM package was in charge to upgrade the HTTP connection and manage the websocket one.
This PR moves the connection management (server side) to the server package to split the connection management from TPM authentication.
This will allow us later (part II) to make it easier to pass the smbios data and the labels through the websocket channel instead of abusing HTTP headers.
This PR doesn't introduce any functional change, so doesn't change (nor break) current websocket communication pattern. 
Related to https://github.com/rancher/elemental-operator/issues/5
Partially fixes https://github.com/rancher/elemental-operator/issues/130

machine registration connectivity rework - part I

---

cmd/register/main.go
go.mod
go.sum
pkg/register/register.go
pkg/tpm/register.go

This is the client-side equivalent of https://github.com/rancher/elemental-operator/pull/140.
~~Note that this needs first that https://github.com/rancher-sandbox/go-tpm/pull/5 got merged, then this branch will be updated with the new go-tpm version (for this reason got the `blocked` flag).~~ _(merged, blocked flag removed)_
register: take control of the registration process
Till now, the attestation and communication with the elemental operator
were all demanded to the github.com/rancher-sandbox/go-tpm package.
Split TPM attestation from the communication with the elemental operator
demanding TPM authentication to the external library while taking full
control of the communication with the operator.
This doesn't introduce functional changes (so it will keep retrocompatibility
with the …

 machine registration connectivity rework - part II

---

.github/workflows/e2e.yaml
chart/templates/apiservice.yaml
chart/templates/deployment.yaml
chart/templates/rbac.yaml
chart/templates/serviceaccount.yaml
chart/values.yaml
tests/e2e/e2e_suite_test.go
tests/e2e/machineregistration_test.go

Enables deploying either multiple operators.
Changes tests to account and test this
Chart changes:
- Make any fixed names default to the release name. As release name has
to be unique per namespace, this is a good practice instead of
hardcoding whatever name we want. This shouldnt affect anything as
the full chart uses that by default now.

Enable deploying operator replicas

---

pkg/controllers/machineinventoryselector/bootstrap.go

we are setting some custom labels on bootstrap but they are not used
anywhere.
Drop them unless we have a need to set some specific labels on node
bootstrap

drop unused labels on bootstrap

---

chart/templates/apiservice.yaml

This has to be a known value that we can watch for in the operator, this
doesnt require to be unique per deployment as several processes can
watch the same secret

Fix secretname for the apiService

---

pkg/server/register.go
pkg/server/register_test.go

Now that we get the smbios data properly, we can add extra labels to the
inventory based on that smbios data.
This could be helpful to identify groups of machines in big deployments
and adds extra info to the inventory so we can search using selectors
via kubectl.

Add extra labels with smbios data

---

Examples/elemental.cattle.io/v1beta1/MachineRegistration.yaml
Makefile
pkg/generated/clientset/versioned/fake/register.go
pkg/generated/clientset/versioned/scheme/register.go
pkg/server/register.go
pkg/server/register_test.go

This allows to set key/values on the
registration.MachineInventoryLabels that will get parsed into
labels with the help of the smbios data, allowing to set whatever labels
you want to generate via the registration directly
Also fix a bit the sanitation methods to allow data to have dashes and
be uppercase
Sets a specific regex for the machineName as that has more limitations
that labels (no lower dashes, no uppercase)

Configure custom smbios data

---

go.mod
go.sum
pkg/server/register.go
pkg/server/register_test.go

Right now when the MachineRegistration is missing a 'spec.MachineName' value we set the following hostname:
m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}
This causes an invalid hostname if config.registration.no-smbios is set to true, failing the registration.
When no-smbios is set to false instead, we may still fail the registration as the hostname derived by no-smbios data is truncated to 58 chars, which may end up truncating the UUID, which is the only parameter ensuring uniqueness.
So, when SMBIOS data is available (no-smbios == false) the default MachineInventory name got the UUID parameter as the first one (so it will not be truncated); when no SMBIOS is are available instead, the hostname will be set to a random DUID.
Fixes: …

operator: change default MachineInventory name

---

cmd/register/main.go
pkg/config/config.go
pkg/register/register.go
pkg/server/register.go
pkg/server/register_test.go

The right way to set labels for the MachineInventory objs is to set them in the MachineRegistration:spec:machineInventoryLabels, which will be processed by the operator. Drop MachineRegistration spec:config:elemental:registration:labels.
Fixes #161

register/operator: drop MachineInventory labels passed from the client

---

Dockerfile

Because CGO is needed in elemental-register for TPM emulation, but Alpine image uses musl-libc instead of glibc, which causes issues.
Verification run with a software emulated TPM VM: https://github.com/ldevulder/elemental/runs/8267439630

Use BCI Golang image to build image

---

cmd/support/main.go

support: Add k8s logs to support command
support: Rework copyFilesInDir to get full path
support: skip getting k8s resources if no kubeconfig

support command improvements

---

pkg/controllers/registration/registration.go
pkg/server/register.go
tests/controllerHelpers/FakeCore.go

Starting from Kubernetes 1.24, the creation of ServiceAccounts no more triggers the creation of an associated token (Secret) automatically: we need it for the ServiceAccount bound to the MachineRegistation resources.
Explicitly create it in any case.
Fixes https://github.com/rancher/elemental-operator/issues/176

Explicitly create tokens (Secrets) for MachineRegistration ServiceAccounts

---

chart/templates/globalrole.yaml

During elemental-operator helm installation, it has to be also added Elemnetal Administator GlobalRole for Rancher UI users.
Fixes https://github.com/rancher/elemental/issues/332

Add elemental GlobalRole for Rancher UI

---

.github/workflows/gorelease.yaml
.goreleaser.yaml

- publish only binaries instead of a tar.gz of the binaries bundle
- create SBOM as part of the gorelease pipeline
- use github changelog for the release
- sign ALL the things. Binaries, checksum, and even the SBOM
- release also the cert+sig of the generated artifacts

release: enhance release pipeline

---

chart/templates/rbac.yaml

It seems that elemental-operator RBAC ClusterRole was too wide. This change is simplifying it and removing unneeded privileges.
Fixes #https://github.com/rancher/elemental-operator/issues/186

Audit and update elemental-operator RBAC ClusterRole

---

.github/workflows/e2e.yaml
.gitignore
tests/e2e/config/config.go
tests/e2e/config/config.yaml
tests/e2e/e2e_suite_test.go

Collect operator logs after running tests. It's possible to download them from the job summary page.

Collect operator logs after running tests

---

Dockerfile
Makefile
chart/templates/deployment.yaml
cmd/operator/main.go
cmd/operator/operator-kubebuilder/root.go
config/rbac/bases/role.yaml
config/rbac/kustomization.yaml
config/rbac/patches/name_in_role.yaml

This PR adds a new command for running kubebuilder-based code together with the old one and adds a new make task for generating RBAC from code.

Kubebuilder: Run new code and generate RBAC

---

pkg/apis/elemental.cattle.io/v1beta1/machine.go
pkg/controllers/machineinventory/machineinventory.go
pkg/controllers/managedos/template.go
pkg/controllers/registration/registration.go

Mark secrets created and managed by elemental-operator. It is needed for rancher-backup opeator to select them for backup.
Fixes https://github.com/rancher/elemental/issues/396

Label secrets managed by elemental-operator

---

pkg/controllers/registration/registration.go

Label objects created by elemental-operator with
"elemental.cattle.io/managed": "true"
It will used by rancher-backup operator to filter these object and create proper backup from them.

Label other objects created by elemental-operator

---

.github/workflows/build.yaml
.github/workflows/chart.yaml
.github/workflows/docker-master.yaml
.github/workflows/docker-tag.yaml
.github/workflows/e2e.yaml
.github/workflows/gorelease.yaml
.github/workflows/lint.yaml
.github/workflows/unit-tests.yaml
Makefile
scripts/setup-kind-cluster.sh
tests/e2e/config/config.go
tests/e2e/config/config.yaml

Tests latest rancher 2.6.9 + k8s 1.23.X
Adds known test for rancher 2.6.6 + k8s 1.22.X
Updates actions to latests

tests: use latest url for rancher charts

---

.github/workflows/e2e.yaml
scripts/setup-kind-cluster.sh
tests/e2e/config/config.yaml

tests: Add k8s 1.24 and default to rancher 2.6.9

---

codecov.yml

...so, it should not block the merging.

coverity: make patch status informational

---

chart/templates/rbac.yaml
pkg/controllers/registration/registration.go

A Secret referencing a missing ServiceAccount is deleted by the Secret controller.
While we create them one after the other, still the safest path is to create the ServiceAccount first.
Otherwise we may be exposed to a race condition in which:
1. We create the Secret referencing an unexistent ServiceAccount
2. The Secret controller will detect a Secret referencing an unexistent ServiceAccount and will mark it for deletion
3. The ServiceAccount is created with the reference to the Secret
4. The Secret gets removed from the controller: the controller also updates the ServiceAccount removing the linked Secret
So, let's create ServiceAccounts first.
Moreover, let's also update existing ServiceAccounts if we found them without the Secrets: this will fix existing ServiceAccounts (if the …

operator: create ServiceAccounts before their Secrets

---

.github/workflows/chart.yaml
.github/workflows/docker-tag.yaml
.github/workflows/gorelease.yaml

On docker job: sbom job was adding the sha to a tagged release so it failed to find the image
On goreleaser job: job didnt have the proper permissions
fixes #229 
Also bumps some of the actions to fix some deprecations

Fix docker and gorelease jobs

---

.github/workflows/verify.yaml
Makefile
go.mod

This PR adds a new workflow "verify", that runs `make vendor` and `make build-manifests` and compares diffs to ensure that we don't forget to run any of them.

Kubebuilder: Add "verify" workflow

---

controllers/machineregistration_controller.go

Otherwise we will have no Secrets in the ServiceAccount for kubernetes clusters >= 1.24
Fixes: #246

[controller_runtime] add Secret name reference to the ServiceAccount

---

api/v1beta1/condition_consts.go
api/v1beta1/managedosversionchannel_types.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go
pkg/syncer/custom.go
pkg/syncer/json.go
pkg/syncer/syncer.go
tests/controllerHelpers/FakeSyncerProvider.go
tests/e2e/managedosversionchannel_test.go

This PR adds few changes on the syncer logic:
* Makes use of ManagedOSVersionChannel status reason to track if there is an on going synchronization rather than polling for the existence of a synchronization pod or not.
* Adds a logic to stop trying to synchronize after 4 consecutive attempts. If it exceeds the maximum it just programs the next re-sync after the given sync interval instead of immediately retrying.
* Adds some logging and comments here and there.

Improve syncer

---

cmd/support/main.go

- Remove : from names as it may not be supported on some systems
- Fix kubectl finding
- Fix missing kubeconfig in one command
- Store also the resources description
- Add apps, jobs and plans
- Check kubectl/kubeconfig just once
- Add missing namespaces
- Add NetworkManager log

Several improvements to the support command

---

cmd/operator/main.go
cmd/register/main.go
cmd/support/main.go

Easy way of getting the version only. A flag for register/support and a subcommand for the operator
Fixes #261 

Add version commands/flags for all binaries

---

api/v1beta1/managedosversionchannel_types.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go
pkg/syncer/custom.go
tests/catalog/managedosversionchannel.go
tests/controllerHelpers/FakeSyncerProvider.go
tests/e2e/managedosversionchannel_test.go
tests/e2e/upgrades_test.go

This commit adds a rate limiter to the ManagedOSVersionChannel controller to prevent stacking reconcile loops over the same resource in fast rates (doesn't make sense for a ManagedOSVersionChannel). By default the controller runtime already includes an equivalent rate limiter, but starts in the range of milliseconds, starting the exponential rate limiter in the range of seconds is more than enough in this context.
In addition it drops the failures counter in the resource. This counter was supposed to be used to limit the number attempts to sync in case of failure. This was a bad design, status should not keep a counter like this as any change in status triggers a new immediate reconcile loop, hence the counter was reaching the maximum as fast as the controller runtime was executing …

Add a rate limiter to managedosversionchannel reconciler

---

pkg/controllers/machineinventoryselector/bootstrap.go

The yaml marshalling does not play well with '+' in the key.
This commit makes the node-labels hopefully play nice with k3s/rke config again.

Change yaml marshalling of node-labels

---

controllers/machineinventory_controller.go
controllers/machineregistration_controller.go
controllers/machineselector_controller.go
controllers/managedosimage_controller.go
controllers/managedosversionchannel_controller.go
pkg/util/suite_test.go
pkg/util/util.go
pkg/util/util_test.go

This PR sanitizes conditions on all objects. The previous implementation doesn't have any validation for conditions and after the upgrade, we might be getting invalid values. Let's remove all invalid conditions from objects, reconcile loop will set proper conditions anyway later.
More context: https://github.com/rancher/elemental-operator/issues/241#issuecomment-1337661833

Kubebuilder: Remove invalid conditions from objects

---

controllers/machineselector_controller.go
pkg/server/register.go

* operator: fix MachineSelector controller log
* operator: fix MachineRegistration search in registration
Fixes #292
Backport from the controller_runtime branch:
https://github.com/rancher/elemental-operator/pull/280

Kubebuilder: fix MachineRegistration search during registration

---

go.mod
go.sum
tests/catalog/managedosimage.go
tests/catalog/managedosversion.go
tests/catalog/managedosversionchannel.go
tests/e2e/upgrades_test.go
vendor/github.com/rancher-sandbox/ele-testhelpers/helpers/poll.go
vendor/github.com/rancher-sandbox/ele-testhelpers/kubectl/kubectl.go
vendor/modules.txt

Drop legacy catalog for tests

---

pkg/register/register.go

There is no point on having a static seed for the registration when working with emualted tpm. In fact, once the registration is done the seed value is never used again so why not just use a random value onr egister and drop that config?
This makes several machines with emulated tpm work with just one registration+iso and has no downsides that I can see

[tpm] rework emulation tpm to use random seed

---

chart/templates/deployment.yaml
cmd/operator/operator/root.go

With kubebuilder we moved to sigs.k8s.io/controller-runtime logs. Still, the registration part of the operator uses logrus for logging.
The operator debug config just enables verbose logging on the newer controller-runtime logs: allow to enable verbose logging on registration too.
Fixes #298

operator: add back debug logs for logrus (registration)

---

api/v1beta1/types.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_machineregistrations.yaml

Fixes rancher/elemental-operator#296

Add disable-boot-entry flag in install structure

---

pkg/register/register.go

Try first to get the system UUID and derive the seed from there. It still should be unique per system but allows us to reproduce it if needed.
This should be a stepping stone to deprecate setting the random seed manually and resort to always random-seed by default when using emulated TPM

Derive TPM seed from system UUID

---

.github/workflows/unit-tests.yaml
Makefile

- bump ginkgo version
- run vendor before running the tests
- generate coverage
- enable race detections

Improve unit tests

---

api/v1beta1/types.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
controllers/managedosimage_controller_test.go
pkg/elementalcli/elementalcli.go

Noted that `config-dir` options for the install config got lost within the kubebuilder refactor. This is required to be able to pass custom hooks as part of the installation.

Re-add config-dir install flag

---

pkg/elementalcli/elementalcli.go

This PR sets a default path for the `--config-dir` flag in `elemental install` call during registration. 
This is handy if we want to include some specific `config.yaml` to be honored by the `elemental install`. So by default if an ISO includes `/elemental/config.yaml` in the ISO filesystem it will be loaded. This is helpful to provide specific install configuration within the installation media without having adapt the registration crd.

Add default config-dir value

---

cmd/support/main.go

Replace `/tmp/` with `elemental-support-`
Example:
```shell
$ tar tf m-d815bd22-6380-4fd6-a85f-120f9
elemental-support-120771762
elemental-support-120771762/NetworkManager.log
elemental-support-120771762/apps-describe.log
elemental-support-120771762/apps-resource.log
elemental-support-120771762/cattle-fleet-system-fleet-agent-d56d4c7b5-9px68-logs.log
elemental-support-120771762/cattle-system-cattle-cluster-agent-59b7cc4768-jb886-logs.log
elemental-support-120771762/cattle-system-system-upgrade-controller-7f9f559b4f-9vl6h-logs.log
elemental-support-120771762/cos-immutable-rootfs.log
elemental-support-120771762/cos-setup-boot.log
...
```
Fixes #205

Change tar-file layout in elemental-support

---

Makefile

The parallelized number of tests is based on the number of available processors only. The memory usage for the controllers unit-test is big and we end up using quite some RAM. If systems with mmany CPUs and not that huge GBs of RAM (my system has 16 cores and 16GB of RAM) we likely start to hit the swap space.
The end result I get is that if I have less than 8GB free my system starts trashing and becomes unresponsive. Even if I have more than 8GB free I consume some swap space and the tests run slower than when serializing tests! ----
$git clean -fdx; time make unit-tests
With parallelization:
real    0m17.477s
user    2m8.029s
sys     0m14.570s
Without parallelization (with this patch):
real    0m14.271s
user    0m27.395s
sys     0m4.659s

unit-tests: disable parallelization

---

.github/workflows/lint.yaml
.golangci.yml

Starting with 2023 we started having false go-header positives. This was due to two things:
1) we need to add history during the checkout, as the go-header linter
checks if the header in the sources should include the current year
using 'git log' (if it fails, would check the file stats, but that
has been just checked out, so will match current year for sure).
2) the current golangci-lint v1.50.1 is more sensible to the yaml
syntax, in particular to the curly braces: the parser will work
correctly if the curly braces have a space before (and after) the
expression to be evaluated.

linter: fix go-header check

---

pkg/server/register.go

If run on aarch64 there is no info yet from ghw regarding the cpu threads/cores, so we end up with a useless label with zero values.
This patch makes it so its not stored if the value is zero, as youo cant have 0 cores in a cpu
Fixes #320 

Do not store cpu info if not available

---

controllers/machineselector_controller.go

Use gopkg.in/yaml.v2 marshaller instead of sigs.k8s.io/yaml which does not play nice with the yaml struct-tags.
Fixes #318

Fix node-labels regression

---

.github/workflows/e2e.yaml

Since node16 actions are being deprecated and no action seems to be taken.
This commit uses the jaxxstorm/action-install-gh-release action to install the kind binaries instead.

Replace action engineerd/setup-kind

---

pkg/server/api_registration.go

The CloudConfig structure was a serialized interface map: if an old client is detected, convert back to that legacy type.
Fixes #325

operator: add support to old register clients

---

.obs/dockerfile/Dockerfile
Dockerfile

Picked a non-conflicting uid/gid, tested on v1.24.9-k3s2 with the recommended hardening options.
Fixes #317 

Set default elemental-operator USER

---

pkg/server/api_registration_test.go
pkg/server/server.go

The default machine name is in the format: m-{UUID}.
The UUID is generated via software if SMBIOS data is disabled, otherwise the SMBIOS {System Information/UUID} is used.
Since some hardware vendors don't properly fill the UUID SMBIOS data, let always provide a machine name based on a software generated UUID, to ensure name uniqueness by default.
Fixes #339

operator: always use software UUID as default machine name

---

cmd/register/main.go
pkg/register/register.go
pkg/tpm/register.go

The register client code is tightly coupled with TPM attestation.
While this is not a problem right now as we just support authentication through TPM, it may be good to better separate TPM attestation from the registration process itself for two reasons:
- better code readability
- support of alternative authentication methods
(note that on the operator side the code is already structured to allow alternative authentication methods)
This commit introduces an interface with the required authentication methods: the TPM related code is now completely isolated in the interface implementation.
This PR is made up of commits from #345 which contains only the register client rework, dropping all the functional changes and extensions. So this PR:
- does NOT change any CRD
- does NOT introduce any …

register client: isolate TPM auth code

---

pkg/server/api_buildimage.go
pkg/server/api_buildimage_test.go
pkg/server/registration_cache.go

Add the URL of the built image to the returned data from the build-image API.
Fixes #335 

operator: let build-image API GET to return the image URL

---

pkg/server/api_registration.go
pkg/server/api_registration_test.go
pkg/server/server.go

Remove default MachineInventory labels taken from system (memory, cpu, gpu, network and block devices).
Make these values available as templates on MachineRegistration instead under `${System Data/...}`, for example `${System Data/Memory/Total Physical Bytes}`
Fixes #349 

Move system-data labels to templating

---

api/v1beta1/condition_consts.go
api/v1beta1/machineselector_types.go
api/v1beta1/zz_generated.deepcopy.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_machineinventoryselectors.yaml
config/crd/bases/elemental.cattle.io_machineinventoryselectortemplates.yaml
controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go
controllers/machineregistration_controller.go
controllers/machineregistration_controller_test.go
controllers/machineselector_controller.go
controllers/machineselector_controller_test.go

Make the MachineInventorySelector reference to an owned
MachineInventory a LocalObjectReference, since a resource cannot
own another resource in a different namespace.
Fixes #180 

Turn MachineInventoryRef into LocalObjectReference

---

chart/templates/cluster_role.yaml
cmd/operator/operator/root.go
config/rbac/bases/role.yaml
pkg/server/api_buildimage.go
pkg/server/api_buildimage_test.go
pkg/server/registration_cache.go

This PR adds the actual build of the elemental image in the build-image API.
This is the initial implementation, there are few things that should be improved. A couple:
- review and improve the lifecycle management of the Pod
- switch the container image used to publish the elemental ISO for download
Fixes https://github.com/rancher/elemental-operator/issues/355
Fixes https://github.com/rancher/elemental-operator/issues/356

build-image API: add build job with single pod lifecycle

---

pkg/hostinfo/hostinfo.go
pkg/register/register.go
pkg/server/api_registration.go

This PR isolates the ghw library by making it completely wrapped inside the hostinfo package.
It also adds a couple of template labels (low hanging fruit), in particular the MAC address of the network interfaces.

operator: labels minor improvements

---

pkg/register/register.go
pkg/register/websocket.go
pkg/server/api_registration.go

Allow the registering client to send the remote IP address: we will record it in MachineInventory annotations.
This fixes https://github.com/rancher/elemental/issues/629
This PR also adds a label with the MAC of the real (not virtual) interfaces that we already list as labels in the MachineInventory.
**This is still a PoC** for two main reasons:
- the register client is allowed to send arbitrary data that will be put in annotations.
We should either check the keys at the operator side or at least put a limit on the number of annotations a client can write otherwise we may expose the cluster to some DDOS attack.
- we have to review the data we provide and how we record it (labels/annotations): issue tracked in #349 
~Note: this PR is rebased on #346 to avoid the linter complaining about …

operator: annotate remote host IP 

---

pkg/log/log.go

I believe #370 is caused by passing directly slices as arguments in `pkg/log` rather than passing all values as variadic arguments.
Fixes #370

Use variadic arguments in klog instead of slices

---

cmd/operator/operator/root.go

In CI we face many reconcile loops of machineinventoryselector one after the other and it's logic is highly dependent on having up to date values from resources as it has an adoption logic for another resources everything needs to be in sync to prevent rerunning adoption logic more than once successfully (a single machineinventoryselector adopting two different inventories).
Fixes rancher/elemental#667

Prevent MachineInventorySelector from being cached

---

controllers/machineregistration_controller_test.go

this allows to fix sporadic issues with unit tests:
```
createRBACObjects
should successfully create RBAC objects
/home/fgiudici/go/src/github.com/rancher/elemental-operator/controllers/machineregistration_controller_test.go:202
1.6788283160593388e+09  INFO    Reconciling RBAC resources
1.6788283160594149e+09  INFO    Creating role
1.6788283160648215e+09  INFO    Creating service account
1.6788283160696208e+09  INFO    Creating token secret for the service
account
1.6788283160727391e+09  INFO    Creating role binding
1.678828316076215e+09   INFO    Setting service account ref
------------------------------
• [FAILED] [0.090 seconds]
createRBACObjects
/home/fgiudici/go/src/github.com/rancher/elemental-operator/controllers/machineregistration_controller_test.go:158
[It] should successfully …
```

unit-tests: ensure resources cleanup

---

api/v1beta1/seedimage_type.go
controllers/machineinventory_controller.go
controllers/machineregistration_controller.go

We have removed finalizers from MachineInventories and MachineRegistrations.
Still if we upgrade from older operator versions, we may inherit old resources with the finalizers set there. In this case, when the "old" resources get deleted, no one will remove the finalizers preventing their actual deletion.
Ensure the finalizers are cleaned up if there when the resource is deleted.
Fixes #391

operator: ensure elemental finalizers are removed if present

---

controllers/seedimage_controller.go

... otherwise auto-install would not work:
```
rancher-7934:/system/oem # cat 99_elemental-register.yaml name: "Elemental operator bootstrap"
stages:
network.after:
- if: '[ -f /run/cos/live_mode ] && [ -f
/run/initramfs/live/livecd-cloud-config.yaml ]'
commands:
- systemd-cat -t elemental elemental-register --debug /run/initramfs/live/
```

SeedImage: fix registration yaml name

---

api/v1beta1/condition_consts.go
cmd/operator/operator/root.go
controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go
controllers/machineselector_controller.go
controllers/machineselector_controller_test.go

This PR adds a validation step in the process of adopting a MachineInventory by a MachineInventorySelector.
Machine inventory selectors are all competing to adopt a machine inventory resource. In order to avoid a machine inventory being adopted by more than one selector or vice versa this commit adds a validation process and tracks its status in a new adoption condition for the inventory resource.
The validation process is simple: on one side the machine inventory checks its owner includes the appropriate reference; on the other side the selector checks the reference in status points to a machine inventory owned by itself.
If an inconsistency is found during the validation the adoption process restarts. The bootstrap plan is not created until the adoption process is validated.
Related to …

Fix adoption logic

---

controllers/machineinventory_controller.go
controllers/machineregistration_controller.go
controllers/machineselector_controller.go
controllers/managedosimage_controller.go

This PR is to prevent spurious reconcile loops on MachineInventorySelectors
Fixes #382

Prevent retriggering a reconcile on ownership setup

---

pkg/register/register.go

Just log address if the connection was created successfully. On error the connection might be nil pointer.

Prevent a nil pointer dereference panic error

---

.obs/seedimage/Dockerfile
.obs/specfile/elemental-operator.spec
Makefile

This allows to build in OBS the httpfy package as part of the elemental-operator builds.
It also adds the Dockefile to be used in OBS to build the seed-image-builder container image.
Related to #401 .

httpfy: support automated building

---

pkg/server/api_registration_test.go
pkg/server/server_test.go

Moreover, move functions from server.go to the newer server_test.go.

unit tests: add MAC and Used Memory coverage

---

.obs/workflows.yml

This to ensure the changes are propagated for the seedimage-builder image too

Add seedimage-builder into the OBS workflow

---

api/v1beta1/machineregistration_types.go
chart/templates/cluster_role.yaml
config/rbac/bases/role.yaml
controllers/seedimage_controller.go
controllers/seedimage_controller_test.go
go.mod
pkg/server/api_registration.go
pkg/util/util.go

This PR uses a config map to inject the configuration files into the seedimage-builder container. Basically it allows to simplify the command executed by the pod and it prevents having to download any information that is already managed by the operator such as the registration config yaml.

Use config map in seedimage pod

---

api/v1beta1/condition_consts.go
api/v1beta1/seedimage_type.go
chart/templates/crds.yaml
config/crd/bases/elemental.cattle.io_seedimages.yaml
controllers/seedimage_controller.go
controllers/seedimage_controller_test.go
pkg/util/util.go
pkg/util/util_test.go
utils/httpfy/httpfy.go

This PR adds two new fields to the SeedImage resource, _TimeoutMinutes_ and _RetriggerBuild_.
`TimeoutMinutes`  - it is the deadline (in minutes) after which the Pod containing the built seed image will be deleted once ready. Default is 60 minutes, set to 0 to disable.
`RetriggerBuild` - needed to restart the build process of the seed image (useful if the Pod has been deleted due to an elapsed deadline).
Fixes #397

Seedimage: add automatic cleanup of built images

---

controllers/seedimage_controller.go
controllers/seedimage_controller_test.go
pkg/util/suite_test.go
pkg/util/util.go
pkg/util/util_test.go

This PR allows to pull the base ISO as a container or from an HTTP URL. The logic to use one or the other is based done by parsing the URL, any HTTP URL will use curl to download the ISO and anything else will attempted to be used as a container reference.
Fixes #396

Pull iso as a container

---

controllers/managedosimage_controller.go

This commit makes use of the default and command and image values for ManagedOSImage updateContianerSpec if they are not defined despite having other updateContainerSpec values defined.

Merge default command and image in containersSpec

---

chart/templates/channel-hook.yaml

This commits prevent running a delete before launching the hook.
This prevents a race condition in case the new CRD was not yet cached on the client running the deletion.
Fixes #438

Add channel hook-failed delete policy 

---

.goreleaser.yaml

the SBOM files produced by goreleaser have the following default name for binaries artifacts:
["{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom"]
Just name the SBOM with the artifact name.
Fixes #443

GoReleaser: fix releases CI

---

.obs/workflows.yml

By default we have the image repo enabled in the branched project from the OBS PR workflow: disable it as we don't want to build the ISO there.
Fixes #445

Fix OBS PR workflow

---

Makefile
charts/crds-migration/Chart.yaml
charts/crds-migration/templates/pre-install-hook.yaml
charts/crds-migration/values.yaml
charts/operator/templates/validate-install-crd.yaml

This PR adds a template to the elemental-operator chart to check: 
1. if the elemental crds are installed
2. if the elemental crds are installed with a release name different than the current one
If one of the above checks fails, the installation/upgrade fails with an error message.
The pre-hook for changing the CRDs annotations is no more of use inside the elemental-operator chart and so has been moved to a separate new chart: elemental-operator-crds-migration.
No plan to keep building this new chart for releases, but could be handy to have it around for a while (we may want at some point to build it once).
Fixes #463

Charts: add template checking CRDs installation

---

.obs/dockerfile/Dockerfile

I believe this image should also be under `l3` support.
Part of rancher/elemental#895

Make explicit elemental-operator image is under l3 support

---

api/v1beta1/common_consts.go
controllers/machineinventory_controller.go
controllers/machineregistration_controller.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go

This PR ensures the token secret is kept in the backup tarball. Label `elemental.cattle.io/managed` needs to be set to `true` to actually be included within the backup according to https://github.com/rancher/backup-restore-operator/commit/52640728ca972d03e3b9861bcf28d40cc6819ada
Fixes https://github.com/rancher/elemental/issues/776
**Note**: this PR does not fix any pre-existing resource, so upgrading operator and backing up is not enough to backup pre-existing resources. More specific,  `MachineInventories` and `MachineRegistrations` secrets created by Elemental should switch the label `elemental.cattle.io/managed` value from an empty string to `true`. The same applies for `Roles`, `Rolebindings` and `ServiceAccounts` owned by `MachineRegistrations`. Any MachineRegistration and …

Fix elemental managed label value to match backup operator expectations

---

controllers/machineinventory_controller.go
controllers/machineregistration_controller.go
controllers/machineregistration_controller_test.go
controllers/machineselector_controller.go
controllers/managedosimage_controller.go
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go
controllers/seedimage_controller.go

This commit checks on each reconcile loop if the service account token secret is missing despite being on ready state.
In addition it also adds optimistic locking for patch calls. The motivations is to prevent concurrent controllers to modify outdated data.
Fixes rancher/elemental#776

Recreate service account token secret if missing

---

pkg/elementalcli/elementalcli.go

Before having SeedImages resources this was handy, as the primary way of adding extra configurations during the installation was adding a  `config.yaml` within the ISO. Since ISOs are mostly customized within the cluster as part of the SeedImage built procedure, this is no longer handy and it even turns to be way too convoluted.

Remove custom default config-dir on installation media

---

.obs/chartfile/operator/values.yaml

Fixed a typo in the tag version string for elemental-teal-channel in helm

---

charts/operator/templates/capi_rbac.yaml

CAPI controller was moved into a separate pod, previously it was embedded into Rancher. CAPI controller interacts with elemental resources and this migration requires a separate set of RBAC rules for the new CAPI pod, current permissions are limited to the upstream resources and rancher specific objects, elemental CRs are not included. This PR adds a cluster role with required permissions, it will be merged later as an [aggregated role](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) with the CAPI controller one.

Add CAPI cluster role to helm chart

---

.obs/workflows.yml

Since all services are set to `manual` or `buildtime` in staging, triggering services has no effect. Staging has to be updated manually.
Related to rancher/elemental#971 and rancher/elemental-toolkit#1817

Disable service triggers on staging

---

.obs/chartfile/operator/values.yaml
Makefile
charts/operator/templates/_helpers.tpl
charts/operator/values.yaml

[v1.3.x] Charts: always use camelCase for values

---

Makefile

This is required to actually turn a tag like `v1.4-dev` into `1.4` version of the chart. Otherwise  `make chart` will fail if we add `1.4-dev` development tag.

Apply a regex on tags to match the same criteria as in OBS

---

api/v1beta1/machineregistration_types.go
controllers/seedimage_controller.go
controllers/seedimage_controller_test.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go

This PR ensures it is not possible to generate the registration configuration yaml without a registration URL. It prevents the creation of an ISO without the registration URL, it just errors out instead giving a chance to properly debug it at the right time.
Related to rancher/rancher#42591

Ensure Elemental registration data includes the registration URL

---

scripts/elemental-airgap.sh

Allow to extract and download the OS images specified in the channel image shipped with the Elemental Operator chart.
Build a new channel image targeting the local registry of the airgapped scenario (which is now a mandatory option).
Fixes https://github.com/rancher/elemental/issues/950

elemental-airgap: add support to OS images

---

scripts/generate_mocks.sh

latest, version v0.3.0, causes generate_mocks.sh to fail. Stay on v0.2.0 for now.
Fixes #522

make verify: stay on mockgen v0.2.0

---

api/v1beta1/machineinventory_types.go
api/v1beta1/types.go
charts/crds/templates/crds.yaml
cmd/register/main.go
cmd/register/main_test.go
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go
pkg/install/install.go
pkg/install/mocks/install.go
pkg/register/register.go

Currently the sytem-agent-config is only generated as part of the cloudInitConfigs when installing, but when registering a pre-installed host it is useful to have the option to generate the system-agent-config without install.
This allows us for example to register a pre-installed SLEMicro host via a combustion script which installs then runs elemental-register without the `--install` flag, e.g I've been testing on a VM as below to prove the host registers and shows up in `MachineInventories` without and additional configuration
```
elemental-register --config-path /tmp/elemental-config.yaml --state-path=/tmp/elemental-state.yaml --emulate-tpm --install-local-agent-config --emulated-tpm-seed N
```

register: add no-toolkit CLI option for pre-installed hosts

---

scripts/elemental-airgap.sh

When building the local channel image, if no name is provided, an automatic one is created using the local registry name. Drop the `:` from the registry name if present, otherwise docker tagging will fail with an error.

elemental-airgap: fix automatic image channel name

---

controllers/machineselector_controller.go

One time instructions are always re-applied at system-agent start which triggers rancher provisioning even if the node was already provisioned. This PR prevents re applying bootstrap.sh script if was already successfully applied in the past.
related to rancher/system-agent#126

Prevent recalling bootstrap.sh on 'systemctl restart elemental-system-agent'

---

controllers/machineinventory_controller.go
controllers/machineregistration_controller.go
controllers/machineselector_controller.go

On status patch managed fields are also updated, hence the comparison done always sees a difference even if there was only an status update.

Improve update events filtering to actually ignore status updates

---

api/v1beta1/common_consts.go
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go

This PR adds am owner label to the managedOSVersions created by a channel. This allows to easily fetch owned versions later on for a given channel. Having a map of owned versions allows to easily patch already existing versions.
Note this PR does not apply the label to already existing versions, I have not considered this case for simplicity and because the workaround is as simple as deleting the versions and re-sync again, or deleting and recreating channels. More over this is not a regression in any case.
Deleting ManagedOSVersions is not implemented as I am not sure we have a clear criteria to do so. In any case most of the logic is already there and it could be easily added later on if required.
Fixes #513

Patch already existing versions on channel sync

---

.obs/specfile/elemental-operator.spec

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>
Addresses CVE-2023-44487 and CVE-2023-39325

bump go to 1.20 or later

---

charts/crds/templates/validate-no-pending-deletions.yaml

This PR checks there are no previous CRDs having a deletion time stamp set. If so it assumes these are leftovers of previous installations and refuses to install the crds chart.
For the time being it only checks on machineinventories, however it could be expanded if we consider that necessary. For now I'd keep the check to the minimum.
When trying to install crds chart if the machine inventory is already there with a deletionTimestamp set produces an error like the following:
```bash
$ helm upgrade --install -n cattle-elemental-system --create-namespace \
elemental-operator-crds \
oci://registry.opensuse.org/isv/rancher/elemental/pr/rancher/elemental-operator/pr-553/charts/rancher/elemental-operator-crds-chart …
```

Prevent installing if previous CRDs are pending to be removed

---

controllers/seedimage_controller.go
controllers/seedimage_controller_test.go

When a seedimage resource is reconciled the output-name should stay the same since it's mounted into a pod and the pod will not pick up changes automatically.

Keep old output-name

---

pkg/install/install.go
pkg/install/install_test.go

disk.Name only contains name, not path (eg sda not /dev/sda).
This commit fixes the logic so users can specify either the name or path and elemental will install to the correct device.

Fix device-selector logic

---

.obs/dockerfile/seedimage/Dockerfile

Getting the following error when building a raw disk image using a seedimage-builder from dev:
```
DEBU[2023-11-23T14:06:30Z] Running cmd: 'grub2-editenv /iso/build/oem/grubenv set next_entry=recovery'
ERRO[2023-11-23T14:06:30Z] Error running command: exec: "grub2-editenv": executable file not found in $PATH
ERRO[2023-11-23T14:06:30Z] Failed setting grub variables:
ERRO[2023-11-23T14:06:30Z] failed setting firstboot menu entry: exec: "grub2-editenv": executable file not found in $PATH
ERRO[2023-11-23T14:06:30Z] Woophs, something went terribly wrong: 1 error occurred:
* exec: "grub2-editenv": executable file not found in $PATH
```

Add grub package to seedimage built in OBS

---

controllers/managedosversionchannel_controller.go

During upgrades we have a race-condition for the ManagedOSVersionChannels.
This commit checks to see if a ManagedOSVersionChannel syncer pod was created with another image than the provided elemental-operator and if true, will delete the old pod and recreate the syncer pod.

Fix channel sync bug racy symptom

---

.obs/chartfile/crds/templates/crds.yaml
api/v1beta1/seedimage_type.go
config/crd/bases/elemental.cattle.io_seedimages.yaml
controllers/seedimage_controller.go
controllers/seedimage_controller_test.go

TargetPlatform is used when building raw disk-images for other platforms. An example being building rpi images on a cluster running on x86_64 hardware.

Add TargetPlatform to SeedImageSpec

---

controllers/seedimage_controller.go

This ensures `elemental-register --reset` is run with all needed dependencies satisfied (mainly time-sync for the rpi).

Use reset service as raw disk deploy command

---

.obs/specfile/elemental-operator.spec

go-tpm-tools fails to build on other archs, e.g. s390x.
See bsc#1218560

Restrict package arch to x86_64 and aarch64

---

.obs/dockerfile/seedimage/Dockerfile
.obs/specfile/elemental-operator.spec
hooks/01_rpi-firmware.yaml

The elemental-seedimage-hooks package contains hooks to copy rpi firmware when building a raw disk image.

Add elemental-seedimage-hooks package

---

pkg/hostinfo/hostinfo.go
pkg/runtime/info.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go

Add new `${System Data/Runtime/Hostname}` key to the registration data sent from the elemental-register command.
Fixes #591

Add hostname to system-data

---

Makefile

repo name changed from "elemental-teal-channel" to "elemental-channel": fix it for local builds

Charts/Makefile: fix default OS channel repo name

---

controllers/machineselector_controller.go

The /etc/hostname file is a symlink file re-created at every elemental boot. The symlink used to point to /usr/local/etc/hostname. For forthcoming images, the symlink will point to
/run/elemental/persistent/etc/hostname.
Let's stay on the safe side: let's update the hostname at that location too.
Fixes #601

hostname: set the hostname on the newer location too

---

Makefile
cmd/operator/operator/root.go

Closes #598 
Now looks like: 
`Operator version v1.5.0-dev, architecture amd64, commit 7685cc1bf37f99687db6b7e44b91bedc798f5731, commit date 2024-01-30T09:20:04Z`

Print system architecture

---

pkg/elementalcli/elementalcli.go

Normally both options are on by default, but this slipped through.

Fix inversed reset options

---

controllers/seedimage_controller.go

The --unprivileged flag was removed and --system was added.
https://github.com/rancher/elemental-toolkit/pull/1906

Update seedimage build-disk command

---

.github/dependabot.yml
.github/workflows/build.yaml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/docker-master.yaml
.github/workflows/docker-tag.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/release-chart.yaml
.github/workflows/unit-tests.yaml
.github/workflows/verify.yaml

Use the newer versions of:
* actions/cache             -> v4
* actions/checkout          -> v4
* actions/setup-go 	    -> v5
* actions/download-artifact -> v4
* actions/upload-artifact   -> v4

Bump github actions

---

Dockerfile.seedimage
Makefile

Since leap does not include a compatible version of xorriso, switch back to tumbleweed.
Got errors when trying to install util-linux package on tumbleweed, but it does not seem to be needed.
Logs from seedimage builder:
```shell
$ kubectl logs -n fleet-default fire-img -f -c build
xorriso 1.5.6 : RockRidge filesystem manipulator, libburnia project.
...
```
Fixes #623

Use newer xorriso

---

controllers/seedimage_controller.go

The new `--system` flag should be next to `$(ELEMENTAL_BASE_IMAGE)`

SeedImage builder arguments in wrong order

---

Makefile

In the Makefile we try to install a hardcoded ginkgo version.
This commit uses the ginkgo version in the go.mod file instead.
It hopefully fixes the following warning in the actions logs:
```
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.3.1
Mismatched package versions found:
2.12.1 used by e2e
```

Use go.mod ginkgo version

---

Makefile

COMMITDATE [got lost some time ago](https://github.com/rancher/elemental-operator/commit/0edac918535b95c0e7a4035ddbeb0e38cb8ddce3).
Let's have it back and in the meanwhile drop RAWCOMMITDATE which seems no longer used anywhere.
from:
```
$make register
CGO_ENABLED=1 go build -ldflags '-w -s -X "github.com/rancher/elemental-operator/pkg/version.Version=v1.5.0-dev" -X
"github.com/rancher/elemental-operator/pkg/version.Commit=634cf69a78452716e673d412ea5f77b1085bd565" -X
"github.com/rancher/elemental-operator/pkg/version.CommitDate="' -o build/elemental-register /home/fgiudici/go/src
/github.com/rancher/elemental-operator/cmd/register
$./build/elemental-register -v
I0216 19:38:05.272391   20376 log.go:42] Register version v1.5.0-dev, commit
634cf69a78452716e673d412ea5f77b1085bd565, commit …
```

Makefile: fix commit date for local builds

---

Makefile

The seedimage-builder image is needed to install the built chart: let's add it to the setup-full-cluster target.

Makefile/setup-full-cluster: build seedimage-builder image too

---

pkg/register/register.go

While there also add one more annotation to track the elemental-register version.
Fixes https://github.com/rancher/elemental/issues/1192

elemental-register: collect OS data for MachineInventories annotations

---

.obs/chartfile/operator/Chart.yaml
.obs/chartfile/operator/README.md
.obs/chartfile/operator/questions.yaml
.obs/chartfile/operator/templates/channel.yaml
.obs/chartfile/operator/values.yaml
Makefile

Mainly, change the var "channel.repository" to "channel.image": "repository" var values are collected by the Rancher Marketplace for air gap support. Anyway, in the case of the Elemental Channel, the image should be re-generated in case of air gap scenario following the official Elemental docs.
Also note that now the channel.image should contain the full url, not prepended with teh registryUrl or the systemDefaultRegistry.
Fixes: #649

charts: backport changes from Rancher Marketplace chart

---

api/v1beta1/types.go

This commit removes some omitempty flags in CRDs defintions to make them more verbose and less confusing from the user perspective.

Review omitempty flag on API json converter

---

.obs/chartfile/operator/templates/cluster_role.yaml
config/rbac/bases/role.yaml
controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go
controllers/suite_test.go

Part of rancher/elemental#1268
This PR makes the ManagedOSImage an editable resource. 
It is intended that in order to bump the OS version on all targeted clusters for example, it should be enough to update the `ManagedOSImage.Spec.osImage` field. The linked bundle will be updated if there are any changes and the `system-upgrade-controller` running on the Elemental node should execute it again.

Enable ManagedOSImage updates

---

.obs/chartfile/crds/templates/crds.yaml
Makefile
api/v1beta1/managedosimage_types.go
config/crd/bases/elemental.cattle.io_managedosimages.yaml
controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go
tests/catalog/managedosimage.go
tests/e2e/upgrades_test.go

This PR enables drain options by default on `ManagedOSImages`
With defaults:
```yaml
drain:
force: true
skipWaitForDeleteTimeout: 60
```

Drain nodes by default on upgrade

---

.obs/chartfile/crds/templates/crds.yaml
api/v1beta1/managedosimage_types.go
config/crd/bases/elemental.cattle.io_managedosimages.yaml

Align to this: https://github.com/rancher/system-upgrade-controller/blob/master/pkg/upgrade/job/job.go#L316

Align DrainSpec to system-upgrade-controller defaults

---

scripts/elemental-airgap.sh

Allow run command to work for every (known!) versions.
Tested on my local lab with Stable (1.4.20) and Dev (1.6.0) versions.

[Airgap] fix channel.json extraction

---

cmd/support/main.go
controllers/machineinventory_controller.go
controllers/seedimage_controller.go

Use /run/elemental to check on recovery state and add 'elemental-*` services to support log collection.

Use /run/elemental and elemental- services

---

pkg/server/api_registration.go
pkg/server/api_registration_test.go
pkg/server/server.go

The MachineRegistration 'machineName', when set is used as the blueprint for generating the MachineInventory name.
The MachineInventory name is set on the associated host as the hostname during k3s/RKE2 provisioning.
With the recent introduction of the hostname data label, we allow the users to use the pre-registration hostname of the host as the machine inventory name (which will be later enforced as the static hostname).
This could be useful to preserve an hostname assigned by a DHCP server.
Hostnames assigned from a DHCP server usually ends with the network domain name of the organization.
Current sanitization of the "data-labels" (hw-labels and SMBIOS labels) do not allow dots, which are replaced with hypens.
Since the Registration 'machineName' field, and so the MachineInventory …

Allow dots in the hostnames / MachineInventory names

---

controllers/seedimage_controller.go
pkg/server/api_seedimage.go

Closes #673 
This makes the URL a bit more readable: 
```
downloadURL: https://172.18.0.2.sslip.io/elemental/seedimage/2gb2ctz4ptb8c5ww4pmnkvnmbtlbw7fbxjt98rldq6r6c67wqj8h6p/fire-nodes.iso
```
It's also backward compatible, so that querying `https://172.18.0.2.sslip.io/elemental/seedimage/2gb2ctz4ptb8c5ww4pmnkvnmbtlbw7fbxjt98rldq6r6c67wqj8h6p` is working as expected for all those SeedImages already built.

Add extension to seedimage url

---

.github/workflows/airgap-test.yaml
Makefile
scripts/elemental-airgap-test.sh
scripts/elemental-airgap.sh

Will build a channel OS image for a private registry using the stable, staging and dev charts links.
Will check the OS URLs generated inside the new channel image for the private registry.
Add the test to a new github workflow to be ran on each new PR.
Fixes #666

[Airgap] add basic tests for the airgap script

---

.obs/chartfile/operator/templates/deployment.yaml

When installing the chart, the deployment would render as:
```
apiVersion: apps/v1    
kind: Deployment
metadata:
labels:
app.kubernetes.io/name: elemental-operator
app.kuberentes.io/version: 1.6.0
name: elemental-operator                                                     
spec:                                                                          
replicas: 1                
selector:
matchLabels:
[...]
```
Fixes #691

chart: add chart name and version to the operator deployment

---

pkg/plainauth/plainauth.go
pkg/plainauth/register_test.go
pkg/register/register_test.go
pkg/server/api_registration_test.go
pkg/server/api_seedimage_test.go

This PR start adding some tests to cover the registration code.
The tests require a HTTP Mock server. Checked the promising [Gomega ghttp package](https://onsi.github.io/gomega/#codeghttpcode-testing-http-clients) but unfortunately we need an HTTP server that supports websocket upgrades.
So, ended up with an httptest.Server{} upgraded to websocket, used in the test just as an echo server.
There is also a commit adding some tests for the seedimage API: the tests there are not using ginkgo, but are more coherent with the tests running on the register-api section (probably we should covert all).
While there is still much more code to be covered for the registration part, this PR is a nice starting point (or so I hope 😆 ).
Related to https://github.com/rancher/elemental-operator/issues/454

Unit tests: add some more coverage to registration and seedimage API

---

controllers/seedimage_controller.go

When building an ISO, we create a Pod and a Service to expose the built
ISO when ready.
The link to the ISO is then exposed through the Elemental Operator
Deployment, that acts as an Ingress.
The Service we create to expose the Pod port is of type NodePort: this
is not needed,is just a leftover from the initial implementations, where
we usede to expose a "direct" link to the Pod.
No need to keep a NodePort service now, let's have a ClusterIP Service
type instead.
Fixes https://github.com/rancher/elemental-operator/issues/705

Seedimage: use a ClusterIP Service and clean it up immediately when not needed.

---

controllers/seedimage_controller.go

backport of #709 
----
When building an ISO, we create a Pod and a Service to expose the built ISO when ready.
The link to the ISO is then exposed through the Elemental Operator Deployment, that acts as an Ingress.
The Service we create to expose the Pod port is of type NodePort: this is not needed,is just a leftover from the initial implementations, where we usede to expose a "direct" link to the Pod.
No need to keep a NodePort service now, let's have a ClusterIP Service type instead.
Fixes: https://github.com/rancher/elemental-operator/issues/705
(cherry picked from commit a43c150c82dae57de29dd386455e096b7903e17d)

[v1.5.x][BACKPORT] seedimage: use ClusterIP Services (#709)

---

controllers/seedimage_controller.go

backport of #709
----
When building an ISO, we create a Pod and a Service to expose the built ISO when ready.
The link to the ISO is then exposed through the Elemental Operator Deployment, that acts as an Ingress.
The Service we create to expose the Pod port is of type NodePort: this is not needed,is just a leftover from the initial implementations, where we usede to expose a "direct" link to the Pod.
No need to keep a NodePort service now, let's have a ClusterIP Service type instead.
Fixes: https://github.com/rancher/elemental-operator/issues/705
(cherry picked from commit a43c150c82dae57de29dd386455e096b7903e17d)

[v1.6.x][BACKPORT] seedimage: use ClusterIP Services (#709) 

---

.obs/chartfile/operator/templates/deployment.yaml

Re-adding this commit as those labels are part of the recommended labels for a deployment resource. So even if in the future this is not a strict requirement from the UI I think it is a good practice to keep them.
This also keeps backward compatibility, fixes rancher/elemental-ui#178

chart: add chart name and version to the operator deployment (#694)

---

controllers/seedimage_controller.go

We used to just clean-up the Pod carrying the built image when hitting the cleanupAfterMinutes deadline.
There is no need to leave the Service around, clean that up too.
Fixes #704

seedimage: clean-up service on image download deadline

---

.obs/chartfile/operator/Chart.yaml

`upstream-version` metadata is wrong:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: Metadata
metadata:
[...]
spec:
annotations:
catalog.cattle.io/auto-install: elemental-operator-crds=match
[...]
catalog.cattle.io/upstream-version: '%VERSION'
appVersion: 1.7.0
```

chart: fix upstream-version metadata

---

controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go

This should address a problem when using dots on the `ManagedOSImage` name.
For example you could use `update-to-2.0.2` when creating a new Upgrade Group from the Elemental UI, and this is perfectly valid. 
However, at the end of the upgrade process, the system-upgrade-controller will re-use this name to set the upgrade Pod's Volume, which must be in DNS Label standard (no dots allowed). 
```
Invalid value: \"secret-os-upgrader-update-to-2.0.2\": must not contain dots,
```
This PR introduces a simple conversion to DNS Label standard, which should be safe to perform and doesn't bother the user.

Prevent system-upgrade-controller from using dotted names

---

.github/actions/chart/action.yaml
.github/workflows/airgap-test.yaml

This should no longer be needed, as it's included in the runner images: https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-yq.sh

Deprecate install yq action

---

controllers/seedimage_controller.go
controllers/seedimage_controller_test.go

This commit makes use of the targetPlatform field on the seedImage spec
to allow building ISOs for different architectures.
It does this by spawning the initContainer using the seedImageBuilder
image and using the `elemental pull-image --platform=` command to
download the correct ISO and copies it to the attached volume.
One drawback of this approach is we don't get the caching of images in
the container runtime that we get when building natively.

Allow cross build of seed-image ISOs

---

controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go

This PR adds functionality that enables unmanaged OS nodes in Elemental to utilise the reset functionality of the Elemental operator. The functionality here enables an OS-agnostic approach, where it simply leaves a marker on the underlying host when reset via Rancher is explicitly desired in the event of either a cluster deletion, node deletion from cluster, or node deletion from the machine inventory. This PR doesn't add the actual handling of the cleanup here, and leaves that for the user in question, e.g. triggering via systemd cleanup script. This enables the user to handle the node cleanup via whatever means they desire, but knowing that it was originally triggered by Rancher/Elemental, and thus data cleanup is likely desired, but isn't controlled by Elemental.
This patch requires …

Added the ability to create a node reset marker for unmanaged hosts

---

controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go

Backport of #731 
NOTE: Replacing `systemagent.Plan` with `applyinator.Plan` for backport to succeed and tests pass.
Signed-off-by: Rhys Oxenham (rhys.oxenham@suse.com)
(cherry picked from commit 7c71dc9de1a24a8ca44e67c39322e6772e763b12)

[v1.4.x][BACKPORT] Added the ability to create a node reset marker for unmanaged hosts (#731)

---

controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go

Backport of #731
Signed-off-by: Rhys Oxenham (rhys.oxenham@suse.com)
(cherry picked from commit 7c71dc9)

[v1.6.x][BACKPORT] Added the ability to create a node reset marker for unmanaged hosts (#731)

---

pkg/hostinfo/hostinfo.go
pkg/register/register.go

The newer versions of jaypipes/ghw include a new type of Disk and Controller in the Blocks section.
We use the library json serialization functionality: the deserialization function of the older version of the library (0.9.0) would error out when trying to decode serialized data of newer versions if they include the new "virtual" drive or the new "loop" controller. For now, just remove those devices.
Proper fix will be to better deal with this kind of errors avoiding tearing down the registration process.
(cherry picked from commit 3379c85c4076e2c334e7a3692d5334c1321720de)

[ v1.5.x][BACKPORT] register: don't send new Disks and Controllers data

---

pkg/hostinfo/hostinfo.go
pkg/register/register.go

The newer versions of jaypipes/ghw include a new type of Disk and Controller in the Blocks section.
We use the library json serialization functionality: the deserialization function of the older version of the library (0.9.0) would error out when trying to decode serialized data of newer versions if they include the new "virtual" drive or the new "loop" controller. For now, just remove those devices.
Proper fix will be to better deal with this kind of errors avoiding tearing down the registration process.
(cherry picked from commit 3379c85c4076e2c334e7a3692d5334c1321720de)

[ v1.6.x][BACKPORT] register: don't send new Disks and Controllers data

---

pkg/hostinfo/hostinfo.go
pkg/register/register.go
pkg/register/websocket.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go

This should remove the `elemental-operator` dependency on ghw library, making the `elemental-register` client do the conversion. 
The implementation is backward compatible, tested it with a `1.4.2` version of the elemental-register and it works as expected.
This is a solution for #733 and if integrated, it should be backported to 1.6.x in order to close that issue.

Let elemental-register digest system hardware data

---

api/v1beta1/common_consts.go
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go

This introduces a `elemental.cattle.io/channel-no-longer-in-sync` annotation that can be used by the UI (or by the user directly) to cleanup no longer synced versions from a channel. 
Closes #744

Flag no longer in sync ManagedOSVersions

---

api/v1beta1/common_consts.go
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go

* Flag no longer in sync ManagedOSVersions

[v1.6.x backport] Flag no longer in sync ManagedOSVersions

---

go.mod
pkg/util/util.go
pkg/util/util_test.go

Closes rancher/elemental#1437
@davidcassany This is what I had in mind. 
(Still have to test it, but it should work)
Whenever the user can define a "cloud config", the elemental-operator codebase always assumed it was cloud-init style, therefore it always prefixed the `#cloud-config` header. 
With this patch we try to figure out if this is a yip config (technically if at least one stage has been defined), before applying or not the  `#cloud-config` header. 
I also removed the custom mapping code and used `sigs.k8s.io/yaml` which contrary to our code, works when working with maps (as `stages` is in yip)

Allow yip configs

---

controllers/managedosversionchannel_controller.go

Review the sync in the ManagedOSVersionChannel reconcile loop.
After the very fist initial sync, all subsequently channel syncs fail: fixed.
Fixes: #766 
Older resources may not have annotations yet: initialize the field.
Fixes: #767

operator: fix ManagedOSVersionChannel sync

---

cmd/support/main.go
internal/system-agent/api.go
pkg/install/_testdata/system-agent-config.yaml
pkg/install/install.go

Use YAML content for Elemental Agent config (#765)

---

controllers/managedosversionchannel_controller.go

...also if we have an error on Pod creation.
Thanks @davidcassany for reporting it 🙇🏼‍♂️ 
Fixes commit 5ccde141e687e20788acb62542660369b9e47861

operator: always update managedosversionchannel last sync time

---

controllers/machineinventory_controller_test.go

Just a little thing bugging me. 
The "unmanaged reset plan" is a simple sentinel file containing a `time.Now()` timestamp.
We didn't expose the controller's clock to make it testable, so the checksum test has chances to fail on a slow machine (precision is seconds). 
will look like: 
```
handle unmanaged finalizer [It] should update secret with reset plan when unmanaged annotation is true
/elemental-operator/controllers/machineinventory_controller_test.go:644
[FAILED] Expected
<string>: "cef759..."
to equal       |
<string>: "457f15..."
In [It] at: /elemental-operator/controllers/machineinventory_controller_test.go:661 @ 06/21/24 13:08:13.001
```
Simplest solution is to remove this test for this plan, since the same logic is already tested by the similar "should update secret with reset …

Remove flaky checksum test

---

.obs/chartfile/crds/templates/crds.yaml
Makefile
api/v1beta1/managedosversionchannel_types.go
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go

Part of #759 
This introduces an option to automatically delete ManagedOSVersions that are no longer in sync with a channel.
The default value is `false` to not change the current behavior, but we can rethink it. It should be safe to enable it by default, in conjunction with #775, but it may still be unexpected for the user.

Add toggle to automatically delete no longer in sync versions

---

.obs/chartfile/operator/templates/channel-dev.yaml
.obs/chartfile/operator/templates/channel.yaml
.obs/chartfile/operator/values.yaml

This is a PoC to add an unstable channel for helm builds happening at `isv:Rancher:Elemental` projects in OBS.

Integrate a development channel in charts

---

.obs/chartfile/crds/templates/validate-no-pending-deletions.yaml
.obs/chartfile/operator/templates/validate-install-crd.yaml

With #775 reinstalling elemental-operator with helm results in a broken installation. This change is to prevent reinstalling CRDs if there are still instances pending to be deleted.
This will prevent from having silently broken installations. This is the same issue as in #515

Block reinstall if crds are still pending to be deleted

---

.obs/chartfile/crds/templates/crds.yaml
Makefile
api/v1beta1/managedosversionchannel_types.go
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go

[v1.6.x]  Add toggle to automatically delete no longer in sync versions (#780) 

---

controllers/machineinventory_controller_test.go

In GHA we sporadically see equaity check to fail because the underlaying slice arrays of a []byte pair are having a different capacity despite having the same lenght and content.
Failed run example https://github.com/rancher/elemental-operator/actions/runs/9694789636/attempts/1

Workaround []byte equality check

---

.obs/chartfile/crds/templates/crds.yaml
.obs/chartfile/operator/templates/validate-install-crd.yaml
config/crd/kustomization.yaml

Added some annotations and labels for the CRDs chart based on https://v2.helm.sh/docs/chart_best_practices/#standard-labels 
With them we can add a validation to check CRDs chart and Elemental-Operator chart are aligned with the same version.

Check crds chart is aligned with the main operator chart version

---

.obs/chartfile/crds/templates/crds.yaml
.obs/chartfile/operator/questions.yaml
.obs/chartfile/operator/templates/channels.yaml
.obs/chartfile/operator/values.yaml
Makefile
api/v1beta1/condition_consts.go
api/v1beta1/managedosversionchannel_types.go
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go
controllers/managedosversionchannel_controller_test.go
tests/catalog/managedosversionchannel.go

Closes rancher/elemental#1462
This PR introduces a new `ManagedOSVersionChannel.spec.enabled` flag that can be used to disable a channel.
Channels are always enabled by default, so disabling has to be explicit. 
Disabling channels will also flag all linked ManagedOSVersions as no longer in sync.
Additionally, if `ManagedOSVersionChannel.spec.deleteNoLongerInSyncVersions` is true, all linked ManagedOSVersions will be flagged for deletion.

Implement Enabled field on ManagedOSVersionChannels

---

pkg/hostinfo/hostinfo.go
pkg/register/websocket.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go
pkg/server/labeltmpl.go
pkg/server/server.go
pkg/templater/templater.go
pkg/templater/templater_test.go

Reworked the code to provide templating to MachineInventory labels and name.
The template source data is the "System Information" (BIOS) and "System Data" (which we usually called 'HW Labels') data sent by the machines via the register client.
This rework fixes some bugs and duplicated code and slightly changes the behavior in few cases.
The behavioral changes address the following corner cases:
* `.` is added to the allowed characters in label values (previously was substituted with `-`).
* when the first character of a label value is an accepted one but not alphanumeric (i.e., `-` , `_` or `.`) we drop it (previously we prepended `m` to the label).
* if the last character of a label value is not alphanumeric (i.e., `-` , `_` or `.`) we drop it (previously was not checked).
note that for …

operator: rework label templating

---

cmd/register/main.go
cmd/register/main_test.go
pkg/install/install_test.go
pkg/register/register.go
pkg/register/state.go
pkg/register/state_test.go

Remove the static check to re-register only after 24 hours. The re-registration will then happen every time the elemental-register client is called.
This static timer was introduced to limit as much as possible the communication form the host to Rancher and save communication bandwidth for remote clients.
Anyway, this makes not much sense as long as the elemental-system-agent is running, which will in any case keep connecting to Rancher. The call to the elemental-register binary is performed on official Elemental SLE Micro images every 30 minutes and at each boot.
Fixes https://github.com/rancher/elemental-operator/issues/811
(cherry picked from commit 36468aba429ec2e4472b5762b8a400f9c2c363a4)
Backport of #813

[v1.6.x][BACKPORT] register: always register when called

---

cmd/register/main.go

moreover, dump the inner error

linter/trivial: error strings should not be capitalized (ST1005)

---

cmd/register/main.go
cmd/register/main_test.go
pkg/register/mocks/client.go
pkg/register/register.go
pkg/server/api_registration.go

Now the network data is piggybacked to the elemental data during registration.
This way the registering client doesn't need to open a separate connection after the registration is done.

networking: use the main registration websocket channel for network data

---

pkg/templater/random.go
pkg/templater/templater.go
pkg/templater/templater_test.go

introduce built-in random templates:
* ${Random/UUID}
* ${Random/Hex/[0-32]}
* ${Random/Int/[MAXINT]}
examples:
${Random/UUID}		--> e512d5ca-a765-42f2-82b7-264f37ffb329 ${Random/Hex/12}	--> e512d5caa765
${Random/Int/1000}	--> 199
Fixes #802

operator: add built-in 'Random' label templates

---

pkg/server/api_registration_test.go
pkg/server/labeltmpl.go
pkg/templater/random.go

MachineRegistration template labels are rendered to MachineInventory labels at every (re-)registration.
Every Elemental host re-registers regularly, so each time this happens, the MachineRegistration rendered labels overwrite the labels in the MachineInventory resource associated with the host.
This makes sense for the Hardware Template Variables (imagine the host is switched off, changed in the HW, e.g., RAM augmented or CPU swapped, and then rebooted) and for all the Template Variables tracking the host data.
For the recently added Random Template Variables instead this should not happen, otherwise the Random part will be changed at every re-registration.
This PR checks if the MachineRegistration template label to be rendered contains a Random Template Variable and if a value for the …

Random template labels - avoid override

---

.obs/chartfile/crds/templates/crds.yaml
api/v1beta1/managedosversionchannel_types.go
config/crd/bases/elemental.cattle.io_managedosversionchannels.yaml
controllers/managedosversionchannel_controller.go

The new Registry field allows to prepend a common registry to the image URLs of the embedded ManagedOSVersion resources.
Fixes #549

operator: add Registry to ManagedOSVersionChannels Spec

---

cmd/register/main.go
cmd/register/showdata.go
cmd/register/version.go

'dumpdata' allows to inspect host data from the running host as they are collected during the registration phase: those are the data made available in the Elemental Label Templates feature. This subcommand was developed while working at #834 and since could be handy for debugging and even for users (elemental sysadmins) adding it to the elemental-register binary.
'version' is the very first step in moving the elemental-register flags to command, as requested by #832.
Related to issues: #832, #834

register: add 'version' and 'dumpdata'  subcommands

---

.obs/chartfile/operator/questions.yaml

Sets default tag and image repository in questions.yaml to the same values as we have in `values.yaml`
Part of #837

Align values.yaml and questions.yaml

---

cmd/register/showdata.go
pkg/hostinfo/hostinfo.go
pkg/register/register.go
pkg/server/api_registration_test.go

Quite some changes in this PR:
* Allow automatic conversion of data to map[string]interface{} (Label Templates format) using reflection; still, collect manually partial data from the hostinfo data for some subsystems to just pick useful data.
* Use variable names from hostinfo: in particular, drop spaces in variable names.
* Try to keep consistent variable names/path.
* Expose NICs and Disks also by number, to enable listing also when the device name is not known.
* Get SMBIOS data directly from hostinfo with update var names: `System Information` data still transmitted in parallel but deprecated (and when removed we can drop also the dmidecode tool requirement).
* Keep the old variable naming enabled: they should be now deprecated and removed in the future.
The `elemental-registry dump` …

Label Templates: rework collection of 'hostinfo' data and collected variables

---

.obs/chartfile/operator/questions.yaml

Update questions to use SL Micro 6.0 channels

---

pkg/hostinfo/hostinfo.go

was a leftover from label templates rework

label templates: drop spaces from Storage variables

---

.obs/helper_scripts/checkimages.sh
.obs/helper_scripts/listimages.sh

I am not sure about the relevance of this script with the new channels scheme. At a time I coded these scripts to list elemental-operator images and to validate channels, but this is loosing it's meaning, now the contents of OS channels are validated by design (we create the contents of it by querying the actual registry) and the channel image itself is decoupled from the operator.
In any case this is just a trivial patch to keep it up to date and consistent.

Update helper scripts to 1.6.x channel setup

---

.obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
api/v1beta1/types.go
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
pkg/elementalcli/elementalcli.go

Depends on https://github.com/rancher/elemental-toolkit/pull/2193
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
name: fire-nodes
namespace: fleet-default
spec:
elemental:
install:
snapshotter:
type: btrfs
maxSnaps: 2
```
Note that the default (and minimum value) now is `2`. This differs from the previous `4` for `btrfs` snapshotter (was driven toolkit side).   
Also note that this covers `install` phase only. 
I considered implementing it for reset as well, however since you will actually be able to define a different snapshotter config on reset, this will make machine drift in behavior, depending if they are freshly provisioned or reset, which is not desirable imho.
Changing snapshotter type on reset also has consequences, for example switching from …

Allow configuration of max snapshots during install

---

scripts/elemental-airgap.sh

Newer versions of Dev and Staging now need to be explicitly allowed to be pull with Helm.
For verification run see here: https://github.com/rancher/elemental/pull/1591.

[Airgap] Fix script to support Dev and Staging

---

.obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
.obs/chartfile/elemental-operator-helm/templates/deployment.yaml
config/crd/kustomization.yaml

charts: drop chart version from resource labels

---

tests/e2e/e2e_suite_test.go
tests/manifests/cattle-system-namespace.yaml
tests/manifests/test-private-ca.yaml

This PR here is to setup a private CA when installing Rancher. 
This enables testing with CA rotation/expiration and what not.
Also helper for https://github.com/rancher/elemental/issues/1604

Use privateCA for Rancher on dev environment

---

.obs/chartfile/elemental-operator-helm/templates/rbac.yaml
Makefile
config/rbac/bases/cluster_role_binding.yaml
config/rbac/bases/role.yaml
config/rbac/bases/role_binding.yaml
config/rbac/kustomization.yaml
config/rbac/patches/name_in_rolebinding.yaml
controllers/seedimage_controller.go

Do not allow the seedimage-controller to operate on pods, services and configmaps outside of the fleet-default namespace.
This requires to introduce a Role and RoleBinding scoped on fleet-default along our ClusterRole and ClusterRoleBinding for the operator ServiceAccount.
Moved all the RBAC resources above under kustomize management and converted all in a rbac.yaml file under the chart template directory.
Fixes #457

RBAC: restrict SeedImage controller auth to fleet-default

---

.obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
api/v1beta1/types.go
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
pkg/install/_testdata/after-hook-config-install.yaml
pkg/install/_testdata/after-hook-config-reset.yaml
pkg/install/install.go
pkg/install/install_test.go
pkg/server/api_registration.go
pkg/server/api_registration_test.go
tests/e2e/config/config.yaml
tests/e2e/e2e_suite_test.go

Adds support for the [agent-tls-mode](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/tls-settings#agent-tls-enforcement).
In case this Rancher value is missing, we default to `strict` verification, which is the current behavior in elemental-operator.

Add support for agent-tls-mode Rancher setting

---

.obs/specfile/elemental-register/elemental-register.spec

This splits the elemental-operator OBS package in two different OBS src packages. One for the server side and another one for the client side.
This is a PoC around rancher/elemental-obs#26

Split elemental-operator and elemental-register at OBS level

---

.obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
api/v1beta1/machineinventory_types.go
api/v1beta1/types.go
config/crd/bases/elemental.cattle.io_machineinventories.yaml
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go
pkg/network/network.go
pkg/server/api_registration.go
pkg/server/server.go

This PR prevents **always** clearing `/etc/NetworkManager/system-connections/*.nmconnections` during reset.
Instead, the Elemental managed network is reset only if an Elemental NetworkConfig is in use, so that users who are managing network in other ways will not be impacted.
To achieve this, the PR introduces a `none` Network configurator. This will also be used by default, so that it will be clear to the end user that the network is not managed by Elemental when this is the case. 
Any other configurator value is dependent on the schema used in the network config, therefore any other default than `none` should not be set. This is 100% up to the user choice.

Only reset network if a network configurator is used

---

.obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
api/v1beta1/machineinventory_types.go
api/v1beta1/types.go
config/crd/bases/elemental.cattle.io_machineinventories.yaml
config/crd/bases/elemental.cattle.io_machineregistrations.yaml
controllers/machineinventory_controller.go
controllers/machineinventory_controller_test.go
pkg/network/network.go
pkg/server/api_registration.go
pkg/server/server.go

[v1.7.x] Only reset network if a network configurator is used

---

api/v1beta1/managedosversion_types.go

Just to include the newly added `created` timestamp from: https://github.com/rancher/elemental-channels/pull/64
This is an enabler if we want to display the build date of any image to the end user on the UI.

Add created date to the ManagedOSVersion common metadata fields

---

.obs/chartfile/elemental-operator-helm/templates/channels.yaml
.obs/chartfile/elemental-operator-helm/values.yaml

Fix generation of already present resources

---

scripts/elemental-airgap.sh

The airgap script used to work with the Mike Farah's yq.
Anyway, it was incompatible with the Andrey Kislyuk's yq version (which
is the main python3 version you would get via pip).
Make the airgap scriptcompatible with both.
Fixes #897

[Airgap] extend yq support in the airgap script

---

controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go

Add "get" verb for Pod resources.
Fixes https://github.com/rancher/elemental/issues/1702

operator: update RBAC for upgrade plans

---

controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go

Add "get" verb for Pod resources.
Fixes https://github.com/rancher/elemental/issues/1702
Backported from #908

[v1.7.x] operator: update RBAC for upgrade plans

---

controllers/managedosimage_controller.go
controllers/managedosimage_controller_test.go

Add "get" verb for Pod resources.
Fixes https://github.com/rancher/elemental/issues/1702
Backported from #908

[v1.6.x] operator: update RBAC for upgrade plans

---

.obs/chartfile/operator/questions.yaml

Move the tag to 6.1-baremetal also on the questions.yaml file used by the Rancher Marketplace dialog.
align to #abbd2e75fcc01bc3caa78b4dbc2b9ebaa849d3a8

[1.6.x] Fix questions.yaml default tag

---

Dockerfile
Dockerfile.seedimage

Required since x/crypto lib now requires go version >= 1.23
Related to #dd41431b0b2792f0fca005adf3abc3cf471877c4

[v1.7.x] Dockerfile: bump golang container to 1.24

---

pkg/server/labeltmpl.go
pkg/templater/random.go

Fix checking malformed Random template vars (i.e., ${Random}) and avoid failing the whole registration when illegal Random template values are detected: in this case just log an error and skip that specific label only.
Port of #914

[v1.7.x] Label Templates: improve Random family processing

---

pkg/server/labeltmpl.go
pkg/templater/random.go

Fix checking malformed Random template vars (i.e., ${Random}) and avoid failing the whole registration when illegal Random template values are detected: in this case just log an error and skip that specific label only.

Label Templates: improve Random family processing
