rancher/elemental-operator

- go.mod
- go.sum
> Bump image-spec to 1.0.2

- go.mod
- go.sum
> bump github.com/docker/distribution to 2.8.1

- cmd/operator/register/root.go
- pkg/tpm/register.go
- Add debug flag for debug loggin
- Add docs to command
- Add docs to flags
- Pass the cacert via a file, NOT via string
- Rename var config so it doesnt clash with imported package name
> Some register fixes

- .github/workflows/chart.yaml
- .github/workflows/docker.yaml
- .goreleaser.yaml
> Some fixes for the release pipelines

- cmd/operator/register/root.go
> Do not attempt to install in already installed systems

- pkg/config/config.go
> ensure install struct includes proper yaml labels

- cmd/operator/register/root.go
- pkg/config/config.go
- pkg/config/toenv.go
- pkg/config/toenv_test.go
- pkg/server/register.go
- tests/e2e/machineregistration_test.go
> Adds support for cloud-config data in machine registration

- pkg/apis/elemental.cattle.io/v1beta1/zz_generated_deepcopy.go
- pkg/server/register.go
> Do note fetch cloud-config on unauthenticated registartion calls

- pkg/server/register.go
> operator: fix adding machineInventoryLabels after initial registration

- pkg/controllers/machineinventoryselector/inventory.go
> Drop unneeded code

- pkg/config/config.go
Otherwise it wont unmarshall the config properly
> Add missing mapstructure annotations to config

- pkg/config/config_suite_test.go
- pkg/config/toenv_test.go
So we dont drop them in the future
> Couple of tests for config mapstructure

- pkg/controllers/machineinventoryselector/bootstrap.go
> Add missing register command to bootstrap

- Makefile
Signed-off-by: Klaus Kämpf <kkaempf@suse.de>
> Add 'support' to 'make build'

- cmd/register/main.go
> Store all registration data on installation

- Dockerfile
> Add CAs to docker artifact

- .github/labeler.yml
- .github/workflows/labeler.yaml
> Add auto labeler

- tests/e2e/upgrades_test.go
We dropped some of the old releases from the repo so point the upgrade
test to new ones
> Fix e2e discovery tests

- pkg/controllers/machineinventoryselector/bootstrap.go
This commit includes a new local plan to be found by the racher-system-agent installed as part of the bootstrap plan executed by the elemental-system-agent. The only purpose of the new local plan is to stop elemental-system-agent.service after the bootstrap phase is completed.
Fixes #86
> Add local plan to rancher-system-agent to stop elemental-system-agent

- .github/workflows/docker-master.yaml
- .github/workflows/docker-tag.yaml
Fixes https://github.com/rancher/elemental-operator/issues/74
> Add image signing to push jobs

- .codecov.yaml
- .github/workflows/unit-tests.yaml
- codecov.yml
- pkg/controllers/machineinventory/machineinventory.go
- pkg/controllers/machineinventory/machineinventory_test.go
- tests/controllerHelpers/machineInventory.go
> tests(inventory): Add unit tests for inventory methods

- pkg/controllers/registration/registration.go
- pkg/controllers/registration/registration_test.go
- tests/controllerHelpers/FakeCore.go
- tests/controllerHelpers/FakeElementalV1beta1.go
- tests/controllerHelpers/FakeMachineRegistration.go
- tests/controllerHelpers/FakeRBAC.go
- tests/controllerHelpers/FakeRancher.go
- tests/controllerHelpers/FakeSetting.go
- tests/controllerHelpers/FakeSettingCache.go
- tests/controllerHelpers/testClients.go
> tests(registration): More unit tests

- pkg/apis/elemental.cattle.io/v1beta1/machine.go
- pkg/apis/elemental.cattle.io/v1beta1/os.go
- pkg/apis/elemental.cattle.io/v1beta1/registration.go
- pkg/apis/elemental.cattle.io/v1beta1/selector.go
- pkg/controllers/machineinventory/machineinventory.go
- pkg/controllers/machineinventory/machineinventory_test.go
- pkg/controllers/machineinventoryselector/bootstrap.go
- pkg/controllers/machineinventoryselector/controller.go
- pkg/controllers/machineinventoryselector/inventory.go
- pkg/controllers/managedos/managedos.go
- pkg/controllers/registration/registration.go
Add reasons for conditions. This change should add more context to the existing conditions and align us with upstream condition type https://github.com/kubernetes/apimachinery/blob/7fb78ee962897d9de6bac4a8f0f1346eb1480ac4/pkg/apis/meta/v1/types.go#L1464 where reason a required field.
> Add reasons for conditions

- .github/workflows/docker-master.yaml
- .github/workflows/docker-tag.yaml
- .github/workflows/gorelease.yaml
Reverts rancher/elemental-operator#160
Doesnt seem to be working, it cant find the bom command
> Revert "Add sbom to releases and attach to containers"

- .obs/workflows.yml
> Add OBS workflow to update elemental-operator package

- cmd/register/main.go
> Only read yaml files included in the given directories

- pkg/server/register_test.go
Improve operator unit tests coverage a little bit.
Hey coverity, hope this makes you  a little bit happier 😆
> operator: unit-tests: add coverage for unauthenticatedResponse()

- pkg/controllers/machineinventoryselector/bootstrap.go
> Stop elemental-system-agent when the node is ready

- .github/workflows/gorelease.yaml
- .github/workflows/lint.yaml
Part of https://github.com/rancher/elemental/issues/432
> Bump golangci action

- pkg/controllers/machineinventoryselector/bootstrap.go
Inventory labels are not propagated from the inventory into the node so they are pretty useless for things like upgrades.
This patch fixes it by using the override yaml in the node k3s/rke2 configuration to append node labels obtained from the inventory
B rough up in https://github.com/rancher/elemental/issues/509 and the new controllers are not gonna have this issue apparently but the current controllers have so this should fix that issue.
> Propagate inventory labels to node on bootstrap plan

- .obs/workflows.yml
> Also trigger Dev rebuild on tag push

- pkg/controllers/managedos/template.go
- tests/e2e/upgrades_test.go
> Use custom names in upgrade objects

- tests/catalog/manageregistration.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/machineregistration_test.go
Fixes https://github.com/rancher/elemental-operator/issues/240
> Refactor MachineRegistration e2e tests

- tests/catalog/managedosimage.go
- tests/catalog/managedosversion.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/managedosimage_test.go
- tests/e2e/upgrades_test.go
Fix: https://github.com/rancher/elemental-operator/issues/240
> Refactor ManagedOsImage e2e tests

- api/v1beta1/types.go
- chart/templates/cluster_role.yaml
- cmd/register/main.go
- config/rbac/bases/role.yaml
- controllers/machineregistration_controller.go
- pkg/elementalcli/elementalcli.go
- pkg/operator/operator.go
- pkg/server/register.go
- pkg/server/register_test.go
- pkg/server/server.go
- pkg/tpm/auth_tpm.go
- pkg/tpm/tpm.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
> [controller_runtime] operator/registration: switch to Kubebuilder client

- chart/Chart.yaml
- chart/values.yaml
> Change the helm chart oci reference to be aligned with other elemental images

- pkg/register/register.go
- pkg/register/websocket.go
- pkg/server/register.go
Extend the protocol to allow the operator and the remote client to exchange their current protocol version.
Fixes  #265
> [controller_runtime] add registration protocol version

- controllers/machineselector_controller.go
- controllers/managedosimage_controller.go
- controllers/managedosimage_controller_test.go
- tests/e2e/upgrades_test.go
Backport minor fixes from old controllers cc @Itxaka
> Kubebuilder: Backport minor fixes

- controllers/machineselector_controller.go
just skip and update the status to show we are waiting for the inventory.
Fixes #273
> Kubebuilder: don't try to patch an empty MachineInventory

- pkg/operator/operator.go
Related discussion: https://github.com/rancher/elemental-operator/issues/241#issuecomment-1335084419
> Set helm labels on CRDs

- controllers/machineselector_controller.go
- pkg/server/register.go
Clearly a bug... but not so easy to spot 🤦🏼 
Fixes #279
> Kubebuilder: fix MachineRegistration search during registration

- pkg/operator/operator.go
> Add helm labels and annotations to all crds

- pkg/controllers/machineinventoryselector/bootstrap.go
> Remove yaml typo

- controllers/managedosversionchannel_controller.go
- controllers/managedosversionchannel_controller_test.go
> Set default syncTime when not provided

- .github/workflows/e2e.yaml
> Bump rancher version in e2e tests

- .obs/README.md
- .obs/chartfile/Chart.yaml
- .obs/chartfile/values.yaml
- .obs/dockerfile/Dockerfile
- .obs/specfile/elemental-operator.spec
- .obs/workflows.yml
> Add OBS build recipes into the repository

- .obs/chartfile/_helmignore
> Include _helmignore file

- .obs/specfile/elemental-operator.spec
> Fetch commit and date from obsinfo file

- pkg/server/register.go
- pkg/server/register_test.go
> Properly sanitize extra system data

- pkg/register/register.go
> register client: allow to register against lower version operators

- controllers/machineselector_controller.go
- controllers/machineselector_controller_test.go
> Filter inventory list with a labelSelector and not with a labels map

- .obs/workflows.yml
Based on the feedback from https://github.com/openSUSE/open-build-service/issues/13206#issuecomment-1429857569 this should fix rancher/elemental#522
> Remove branch filter on tag events

- Dockerfile
- cmd/operator/display/root.go
- cmd/operator/main.go
- cmd/operator/operator/root.go
- cmd/register/main.go
- cmd/support/main.go
- go.mod
- pkg/clients/clients.go
- pkg/elementalcli/elementalcli.go
- pkg/log/log.go
- pkg/register/register.go
- pkg/server/api_buildimage.go
- pkg/server/api_registration.go
- pkg/server/server.go
- pkg/tpm/auth_tpm.go
- pkg/tpm/register.go
Use klog for all logging and remove logrus.
Fixes #303
> Unify logging

- controllers/machineinventory_controller.go
- controllers/machineinventory_controller_test.go
- controllers/machineregistration_controller.go
- controllers/machineregistration_controller_test.go
- controllers/seedimage_controller.go
- controllers/seedimage_controller_test.go
> Stop using finalizers if not extrictly needed

- controllers/seedimage_controller.go
- controllers/seedimage_controller_test.go
> SeedImage: improve conditions management and add more tests

- .obs/chartfile/values.yaml
- Dockerfile.seedimage
- Makefile
- chart/templates/deployment.yaml
- chart/values.yaml
- cmd/operator/operator/root.go
- controllers/seedimage_controller.go
- controllers/seedimage_controller_test.go
- utils/httpfy/httpfy.go
This allows to create a container image to be used for the Elemental seed image building.
Fixes https://github.com/rancher/elemental-operator/issues/374
> SeedImage: build image for the builder pod

- .obs/dockerfile/Dockerfile
> Build elemental-operator image from scratch

- .obs/chartfile/values.yaml
> OBS: use SeedImage build image from OBS for the chart

- .obs/seedimage/Dockerfile
- Dockerfile.seedimage
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
```
> OBS: add ssl default certificates in SeedImage build image

- controllers/seedimage_controller.go
- pkg/server/api_seedimage.go
- utils/httpfy/httpfy.go
> SeedImage: improve built iso default name

- .obs/chartfile/values.yaml
- chart/templates/channel-hook.yaml
> Include elemental-teal-channel by default on chart install

- .github/workflows/chart.yaml
- .github/workflows/docker-tag.yaml
> SeedImage: add image build to the github release workflow

- .obs/chartfile/Chart.yaml
- chart/Chart.yaml
Few changes to our built chart.
_~In particular, move the crds to the helm 3 crds directory.~
~Should fix #438~._
dropped the change to the crds directory.
This PR just adds small changes to the Chart that will be handy in the Rancher Marketplace (related to #376).
> Chart improvements

- controllers/seedimage_controller.go
> operator: copy cloud-config file, not its link

- api/v1beta1/types.go
- cmd/register/main.go
- pkg/register/register.go
- pkg/register/websocket.go
- pkg/server/api_registration.go
- pkg/server/api_registration_test.go
> Check for live registration config when no arguments passed

- .obs/dockerfile/Dockerfile
> Adds ca-certificates and ca-certificates-mozilla in operator image

- .obs/workflows.yml
- charts/operator/values.yaml
> Update OBS workflow to the new project setup

- .obs/chartfile/operator/values.yaml
fixes #1409e0385fba6d2a9392210b6bbc5760ee09bfe7
> Charts: fix OBS build

- scripts/elemental-airgap.sh
Fixes #503 
./elemental-airgap.sh will download latest Dev chart, extract the images to be loaded on the private registry and print the next steps.
> elemental-airgap: add script to help airgap deployment

- scripts/elemental-airgap.sh
> elemental-airgap: fix skipping http/https URLs

- pkg/install/_testdata/system-agent-config.yaml
- pkg/install/install.go
- pkg/install/install_test.go
As local plan is not used, only remote.
> Disable local plan for elemental-system-agent

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/unit-tests.yaml
- .github/workflows/verify.yaml
- Makefile
- go.mod
- go.sum
- tests/e2e/config/config.yaml
- tests/e2e/e2e_suite_test.go
- tests/e2e/machineregistration_test.go
- tests/e2e/managedosimage_test.go
- tests/e2e/managedosversionchannel_test.go
- vendor/github.com/hashicorp/go-version/CHANGELOG.md
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
- ci: bump k8s and Rancher Manager versions
- ci: fix action versions used
> Fix E2E tests

- scripts/elemental-airgap.sh
...and also to skip archive creation.
This way the script should be ready for usage for the airgap scenario with the chart in the Rancher Marketplace and could allow more custom airgap setup where the images downloaded are pushed to the registry in a different way, without passing through a tar.gz .
Fixes: https://github.com/rancher/elemental-operator/issues/547
> elemental-airgap: allow to just create the channel

- .obs/chartfile/operator/values.yaml
- charts/operator/templates/channel.yaml
- charts/operator/values.yaml
Part of rancher/elemental#1008
> Add slem4r images in channel

- controllers/seedimage_controller_test.go
quay.io shouldn't be used anymore.
> ci: fix SeedImage builder used image

- charts/operator/app-readme.md
- charts/operator/questions.yaml
To test the dev chart installation in the marketplace, we need to add the questions.yaml and app-readme file from https://github.com/rancher/charts/tree/dev-v2.8/charts/elemental/103.0.0%2Bup1.3.4
> Add missing questions.yaml file

- .obs/chartfile/operator/questions.yaml
- Makefile
> Fix default values in questions.yaml file

- controllers/machineselector_controller.go
> Do not adopt machineinventories undergoing deletion/reset

- .github/labeler.yml
- cmd/operator/operator/root.go
- cmd/register/main.go
- cmd/support/main.go
- pkg/server/server.go
- tests/e2e/config/config.go
Revive linter added a new default rule for unused-parameters, update the code to match.
Also includes commit to update labeler configuration file.
> Make linter happy

- Makefile
- controllers/managedosimage_controller.go
- controllers/managedosimage_controller_test.go
- scripts/setup-kind-cluster.sh
- tests/e2e/e2e_suite_test.go
- tests/manifests/test-registry.yaml
Part of rancher/elemental#1202
Note that this also includes a little fix for the OSImage parsing, it did not take in account custom ports on registries.
> Add dev baseimage build

- controllers/managedosversionchannel_controller.go
> Recover on syncer pod creation failures

- controllers/managedosversionchannel_controller.go
Ensure we keep checking synchronization pod status once the syncrhonization started. This is to recover in case there was a missed pod phase change.
Part of #636
> Requeue reconcile loop for ongoing synchronizations

- Makefile
- controllers/managedosversionchannel_controller.go
> Fix channel synchronization

- scripts/elemental-airgap.sh
> [Airgap] add support to Hauler in the airgap script

- scripts/elemental-airgap.sh
Changes made for Rancher Marketplace chart have impacts on the airgap script.
> [Airgap] fix the airgap script

- scripts/elemental-airgap.sh
`channel.image` expects a full image url, including the registry, while `channel.repository` expects the repository url stripped of the registry.
Manage it correctly when printing the next steps.
Fixes #664
> [Airgap] fix "channel.image"/"channel.repository" value in "next steps"

- .obs/chartfile/crds/templates/crds.yaml
- api/v1beta1/managedosimage_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/elemental.cattle.io_managedosimages.yaml
- controllers/managedosimage_controller.go
> Fix ManagedOSImage cloudConfig

- cmd/operator/operator/root.go
- cmd/register/main.go
- cmd/support/main.go
- pkg/server/server.go
- tests/e2e/config/config.go
> [V1.4.x] Make linter happy

- Makefile
- controllers/managedosversionchannel_controller.go
> V1.4.x fix channel synchronization

- pkg/server/api_registration.go
- pkg/server/api_registration_test.go
- pkg/server/server.go
> [v1.4.x]  Allow dots in the hostnames / MachineInventory names

- .obs/chartfile/operator/templates/deployment.yaml
fixes #f965445970522a5ab4194fb6e5f454a4487bbb3f
related to: #691
> chart: fix label typo

- .obs/helper_scripts/README.md
- .obs/helper_scripts/checkimages.sh
- .obs/helper_scripts/listimages.sh
> Add scripts to list and check images from the registry

- .obs/chartfile/operator/templates/deployment.yaml
- .obs/chartfile/operator/values.yaml
drop all privileges and enforce user/group/fsgroup
Fixes: #707
> chart: add customizable security-context

- pkg/hostinfo/hostinfo.go
- pkg/register/register.go
- pkg/register/websocket.go
- pkg/server/api_registration.go
- pkg/server/api_registration_test.go
> (1.6.x Backport) Let elemental-register digest system hardware data

- .obs/chartfile/operator/templates/deployment.yaml
> [v1.6.x] Update deployment.yaml (#757)

- go.mod
PR waiting for https://github.com/github/codeql/issues/15647
This reverts commit b3b80b7864358e2350df1c39e5f1369bb8f6a6cd.
> Revert "CI: fix CodeQL test (#655)"

- cmd/support/main.go
- internal/system-agent/api.go
- pkg/install/_testdata/system-agent-config.yaml
- pkg/install/install.go
Fixes #764 
Should also be backported to 1.6.x
> Use YAML content for Elemental Agent config

- controllers/managedosversionchannel_controller.go
> [v1.6.x][BACKPORT] operator: fix ManagedOSVersionChannel sync 

- cmd/support/main.go
> Use dynamic system agent applied dir

- controllers/managedosversionchannel_controller.go
- controllers/managedosversionchannel_controller_test.go
Backport fixes related to #766
> Backport to v1.5.x

- .obs/chartfile/operator/values.yaml
This PR is to fix the CI, to ensure the CI has an existing channel image available as default
> Add the new default channel

- scripts/elemental-airgap.sh
As OS channel for unstable images is now adding with Helm template the airgap script needs to be adapted to extract it.
This PR keep the old behaviour by default and if asked (with option `--all-channel`) all (unstable for now) channels are also extracted. If no new channel is defined then it runs like before.
Tested on my lab without `--all-channels` option:
```
$ elemental-airgap.sh -d -r rancher-manager.test:5000 -sa dev
[...]
mark rancher/elemental-channel-rancher-manager.test:5.5 image for export
* rancher/elemental-operator:1.7.0
* rancher/seedimage-builder:1.7.0
* registry.suse.com/suse/sle-micro/5.5:2.0.2-4.2.111
* registry.suse.com/suse/sle-micro/5.5:2.0.2-4.2.109
* registry.suse.com/suse/sle-micro/5.5:2.0.2-4.2.107
* registry.suse.com/suse/sle-micro/5.5:2.0.4-5.5.43
* …
```
> [Airgap] fix unstable channel extraction

- .obs/chartfile/operator/values.yaml
This is to add the new list of Micro 6.0 channels in Dev
> Add new Micro 6.0 channels

- Makefile
So now if you build locally, you can use:
```bash
LOCAL_BUILD=true make setup-full-cluster
```
or 
```bash
LOCAL_BUILD=true make reload-operator
```
Makes sense? :D
> Bandaid local build

- scripts/elemental-airgap.sh
This PR should fix [broken airgap CI](https://github.com/rancher/elemental/actions/runs/10436999275). The new code will be compatible with older versions of the operator.
Verification run:
- [CLI-K3s-Airgap](https://github.com/rancher/elemental/actions/runs/10475126426)
> [Airgap] fix channel extraction for 1.7 version

- .obs/chartfile/crds/templates/crds.yaml
- api/v1beta1/seedimage_type.go
- config/crd/bases/elemental.cattle.io_seedimages.yaml
- controllers/seedimage_controller.go
- pkg/server/api_seedimage.go
- pkg/server/api_seedimage_test.go
Backport of https://github.com/rancher/elemental-operator/pull/827
> [v1.6.x] Add SeedImage.status.checksumURL

- .github/workflows/release-chart.yaml
GH release are handled manually
> No need to make any GH release

- .github/workflows/release-chart.yaml
GH release are handled manually
> [v1.7] No need to make any GH release

- .obs/chartfile/elemental-operator-helm/questions.yaml
- .obs/chartfile/elemental-operator-helm/values.yaml
Backport of #883 to v1.6 branch
> [backport] Update default channels to 6.1 images

- .obs/chartfile/elemental-operator-crds-helm/templates/crds.yaml
- api/v1beta1/seedimage_type.go
- config/crd/bases/elemental.cattle.io_seedimages.yaml
Likely an old copy&paste leftover.
> minor: fix SeedImage description

- .obs/chartfile/elemental-operator-helm/templates/channels.yaml
- .obs/chartfile/elemental-operator-helm/values.yaml
> [Backport] Fix generation of already present resources (#892)

- .obs/chartfile/elemental-operator-helm/values.yaml
> [ports  from 1.7.x] Update default channel data

- scripts/elemental-airgap.sh
Adding maintenance case as we are now using maintenance instead of dev.
I do not delete anything now, just adding maintenance.
> Add maintenance case to elemental-airgap.sh
